C     ******************************************************************
C     *                                                                *
C     *    A PROGRAM FOR THE AUTOMATIC COMPUTATION OF STELLAR          *
C     *    EVOLUTION BY THE METHOD OF                                  *
C     *                                                                *
C     *    L. G. HENYEY, J. E. FORBES, AND N. L. GOULD,                *
C     *    ASTROPHYSICAL JOURNAL 139, 306 (1964)  (METHOD II)          *
C     *                                                                *
C     *    THE STAR IS DIVIDED INTO ZONES BY MESH POINTS OF THE        *
C     *    LAGRANGIAN VARIABLE XI, 0 .LE. XI .LE. 1, WITH ALL          *
C     *    QUANTITIES EVALUATED AT THE SAME MESH POINTS.  THE          *
C     *    ARTIFICIAL VARIABLES OF THE PAPER ARE USED THROUGHOUT,      *
C     *         P = (PRESSURE)**(1/4)      (EQ. 8)                     *
C     *         Q = (DENSITY)**(1/3)       (EQ. 9)                     *
C     *         L = XI**2 * F              (EQ. 10, PSEUDOFLUX)        *
C     *         K = 3*KAPPA*P**3/(256*PI*G*SIGMA*T**3)   (EQ. 11)      *
C     *    THE DIFFERENCE EQUATIONS ARE EQS. (22)-(26) OF THE PAPER    *
C     *    WITH BACKWARD TIME DIFFERENCES.  THE LINEARIZED SYSTEM      *
C     *    IS SOLVED BY THE ELIMINATION SCHEME OF EQS. (39)-(46),      *
C     *    WITH THE VECTORS  U = (R,F)  AND  V = (T,Q)  AND THE        *
C     *    RECURSION  DELTA-U(J) + ALPHA(J)*DELTA-V(J) + GAMMA(J) = 0. *
C     *                                                                *
C     *    THE INTERIOR MESH COVERS THE MASS (1-DELS)*M.  THE OUTER    *
C     *    FRACTION DELS = 0.002 IS TREATED BY A SEPARATE ENVELOPE     *
C     *    INTEGRATION (SUBROUTINE ENVEL), WHICH SUPPLIES THE FITTED   *
C     *    BOUNDARY QUANTITIES OF EQS. (30)-(33) AS FUNCTIONS OF THE   *
C     *    TOTAL RADIUS AND LUMINOSITY, IN THE MANNER OF THE VARDYA    *
C     *    OUTER-ZONE PROGRAM REFERRED TO IN THE PAPER.  THE           *
C     *    PHOTOSPHERE IS FIXED BY THE GRAY CONDITIONS                 *
C     *         L = 4*PI*SIGMA*R**2*T**4                               *
C     *         P*KAPPA = (2/3)*G*M/R**2                               *
C     *                                                                *
C     *    THE MATERIAL FUNCTIONS ARE OF THE CLASSICAL KIND - IDEAL    *
C     *    GAS PLUS RADIATION, KRAMERS AND ELECTRON-SCATTERING AND     *
C     *    H-MINUS OPACITY, PROTON-PROTON AND CNO ENERGY GENERATION    *
C     *    (SCHWARZSCHILD 1958).  DEGENERACY IS OMITTED.               *
C     *                                                                *
C     *    INPUT IS READ FROM UNIT 5 (CARD READER).                    *
C     *    OUTPUT IS WRITTEN ON UNIT 6 (LINE PRINTER).                 *
C     *    FORTRAN IV.  SINGLE PRECISION THROUGHOUT.                   *
C     *                                                                *
C     *    CARD 1 (3F10.5)   TOTM   = STELLAR MASS, SOLAR UNITS        *
C     *                      XHYD0  = INITIAL HYDROGEN FRACTION X      *
C     *                      ZMET   = HEAVY ELEMENT FRACTION Z         *
C     *    CARD 2 (2I5,E10.3,F10.5,E10.3,I5)                           *
C     *                      N      = NUMBER OF MESH POINTS (.LE.201)  *
C     *                      NMODS  = NUMBER OF MODELS IN SEQUENCE     *
C     *                      DTYR   = INITIAL TIME STEP, YEARS         *
C     *                      CLIM   = CORRECTION LIMITER (0.1 - 0.3)   *
C     *                      EPSC   = CONVERGENCE TOLERANCE            *
C     *                      NPRIN  = STRUCTURE PRINT INTERVAL         *
C     *                                                                *
C     ******************************************************************
C
C     ------------------------------------------------------------------
C     MAIN PROGRAM - CONTROLS THE EVOLUTIONARY SEQUENCE (FIG. 2 OF
C     THE PAPER).  REACTION-COMPOSITION STEP, HENYEY ITERATIONS,
C     TIME STEP CONTROL.
C     ------------------------------------------------------------------
      COMMON /GRID/ N,XI(201),EMPT(201),EMH(201),EMPH(201)
      COMMON /VARBL/ R(201),F(201),T(201),Q(201),XH(201)
      COMMON /OLDT/ QN(201),EN(201),DTINV
      COMMON /THERM/ PP(201),DPT(201),DPQ(201),EE(201),DET(201),
     1   DEQ(201),CK(201),DKT(201),DKQ(201),CPA(201),EP(201),
     2   DEPT(201),DEPQ(201)
      COMMON /FLAGS/ ICV(201)
      COMMON /CONST/ G,SIG,ARAD,RGAS,PI,C256,C4PS,C8PI
      COMMON /STARP/ XM,XMI,ZMET,QHYD
      COMMON /CTRL/ CLIM,EPSC,ITMAX,ALFA
      COMMON /SURF/ RSTAR,XLSTA,DXR,DXL
      DIMENSION RSV(201),FSV(201),TSV(201),QSV(201),XSV(201),ESV(201)
C
C     PHYSICAL CONSTANTS IN THE SCALED UNITS OF THE ORIGINAL
C     BERKELEY PROGRAM (P. BODENHEIMER, PRIVATE COMMUNICATION) -
C     MASS 1.E30 G, LENGTH 1.E10 CM, TIME 1.E5 SEC, TEMPERATURE
C     1.E7 K.  DENSITY IS THEREBY IN G/CM3 AND THE ACCELERATION
C     IN CM/SEC2, AND ALL WORKING QUANTITIES ARE OF MODERATE
C     MAGNITUDE, WHICH THE 27-BIT SINGLE-PRECISION FRACTION OF
C     THE 7094 REPAYS.  OUTPUT IS CONVERTED TO C.G.S. FOR
C     PRINTING.
      G=666.8
      SIG=5.67E8
      ARAD=7.565E3
      RGAS=8.25E4
      PI=3.1415927
      C256=256.*PI*G*SIG
      C4PS=4.*PI*SIG
      C8PI=8./PI
      SECYR=315.6
C     ENERGY RELEASE PER GRAM OF HYDROGEN CONSUMED
      QHYD=6.3E8
C
C     READ THE CONTROL CARDS (UNIT 5 = CARD READER)
      READ (5,500) TOTM,XHYD0,ZMET
      READ (5,501) N,NMODS,DTYR,CLIM,EPSC,NPRIN,ALFA
      IF (ALFA.LE.0.) ALFA=1.5
      XM=TOTM*1989.
C     THE INTERIOR MESH COVERS THE MASS XMI = (1-DELS)*M.  THE
C     OUTER FRACTION DELS IS CARRIED BY THE SEPARATE ENVELOPE
C     INTEGRATION (SUBROUTINE ENVEL), IN THE MANNER OF THE
C     OUTER-ZONE PROGRAM OF THE PAPER (EQS. 30-33)
      DELS=2.0E-3
      XMI=XM*(1.-DELS)
      WRITE (6,510)
      WRITE (6,511)
      WRITE (6,512)
      WRITE (6,513) XM*1.E30,XHYD0,ZMET
      WRITE (6,514) N,NMODS,DTYR
      WRITE (6,517) ALFA
C
C     SET UP THE FIXED MASS MESH.  THE MASS DISTRIBUTION M(XI) IS
C     NEVER VARIED (SEC. V OF THE PAPER).  WE ADOPT
C         M(XI) = M * XI**3 * (10 - 15*XI + 6*XI**2)
C     WHICH CONCENTRATES THE ZONING AT BOTH CENTER AND SURFACE.
      NM1=N-1
      DO 10 J=1,N
      XX=FLOAT(J-1)/FLOAT(NM1)
      XI(J)=XX
      EMPT(J)=XMI*XX**3*(10.-15.*XX+6.*XX*XX)
   10 CONTINUE
      DO 20 J=1,NM1
      XX=0.5*(XI(J)+XI(J+1))
      EMH(J)=XMI*XX**3*(10.-15.*XX+6.*XX*XX)
      EMPH(J)=30.*XMI*XX*XX*(1.-XX)**2
   20 CONTINUE
C
C     UNIFORM INITIAL COMPOSITION
      DO 30 J=1,N
      XH(J)=XHYD0
      QN(J)=0.
      EN(J)=0.
   30 CONTINUE
C
C     FIRST APPROXIMATION FROM THE EMDEN POLYTROPE N=3
      CALL START(TOTM,XHYD0)
C
C     ------------------------------------------------------------------
C     INITIAL (STATIC) MODEL.  THE TIME DERIVATIVE TERMS ARE
C     SUPPRESSED BY SETTING 1/(DELTA T) = 0.
C     ------------------------------------------------------------------
      DTINV=0.
      ITMAX=60
      MODNO=1
      WRITE (6,515) MODNO
      CALL SOLVE(NIT,IER)
      IF (IER.EQ.0) GO TO 40
      WRITE (6,540)
      STOP 1
   40 CONTINUE
      ITMAX=30
      AGEYR=0.
      DT=DTYR*SECYR
      DTY2=DTYR
      WRITE (6,520)
      XLSOL=XLSTA/3.86E-2
      RSOL=RSTAR/6.96
      TEFF=1.E7*SQRT(SQRT(XLSTA/(C4PS*RSTAR*RSTAR)))
      RHOC=Q(1)**3
      PC=1.E10*PP(1)**4
      WRITE (6,521) MODNO,AGEYR,DTY2,NIT,XLSOL,RSOL,TEFF,1.E7*T(1),
     1   RHOC,PC,XH(1)
      CALL PRINTM
C
C     ------------------------------------------------------------------
C     EVOLUTIONARY SEQUENCE
C     ------------------------------------------------------------------
      IF (NMODS.LE.1) STOP
      DO 300 NMOD=2,NMODS
C     SAVE THE CONVERGED MODEL FOR THE OLD EPOCH AND FOR RETRIES
      DO 210 J=1,N
      QN(J)=Q(J)
      EN(J)=EE(J)
      RSV(J)=R(J)
      FSV(J)=F(J)
      TSV(J)=T(J)
      QSV(J)=Q(J)
      XSV(J)=XH(J)
      ESV(J)=EP(J)
  210 CONTINUE
      RSSV=RSTAR
      XLSV=XLSTA
      NTRY=0
C     COMPOSITION STEP - HYDROGEN DEPLETION BY THE CONVERGED RATES,
C     THEN MIXING OF CONVECTIVE REGIONS (FIRST BOX OF FIG. 2)
  220 DO 230 J=1,N
      XH(J)=AMAX1(XSV(J)-ESV(J)*DT/QHYD,0.)
  230 CONTINUE
      CALL MIX
      DTINV=1./DT
      CALL SOLVE(NIT,IER)
      IF (IER.EQ.0) GO TO 260
C     NO CONVERGENCE - RESTORE THE MODEL, HALVE THE TIME STEP, RETRY
      NTRY=NTRY+1
      IF (NTRY.LE.8) GO TO 240
      WRITE (6,540)
      STOP 2
  240 DO 250 J=1,N
      R(J)=RSV(J)
      F(J)=FSV(J)
      T(J)=TSV(J)
      Q(J)=QSV(J)
  250 CONTINUE
      RSTAR=RSSV
      XLSTA=XLSV
      DT=0.5*DT
      WRITE (6,541) DT
      GO TO 220
C     CONVERGED - PRINT THE TRACK LINE
  260 AGEYR=AGEYR+DT/SECYR
      DTY2=DT/SECYR
      XLSOL=XLSTA/3.86E-2
      RSOL=RSTAR/6.96
      TEFF=1.E7*SQRT(SQRT(XLSTA/(C4PS*RSTAR*RSTAR)))
      RHOC=Q(1)**3
      PC=1.E10*PP(1)**4
      WRITE (6,521) NMOD,AGEYR,DTY2,NIT,XLSOL,RSOL,TEFF,1.E7*T(1),
     1   RHOC,PC,XH(1)
      IF (MOD(NMOD,NPRIN).EQ.0) CALL PRINTM
C     TIME STEP CONTROL - GROW WHEN CONVERGENCE IS EASY, SHRINK
C     WHEN IT IS HARD, AND LIMIT THE CENTRAL HYDROGEN DEPLETION
C     TO ABOUT 3 PERCENT PER STEP
      IF (NIT.LE.5) DT=1.4*DT
      IF (NIT.GE.12) DT=0.7*DT
      DTX=0.03*AMAX1(XH(1),0.02)*QHYD/AMAX1(EP(1),1.E-20)
      DT=AMIN1(DT,DTX,3.E11)
  300 CONTINUE
      CALL PRINTM
      STOP
C
  500 FORMAT (3F10.5)
  501 FORMAT (2I5,E10.3,F10.5,E10.3,I5,F10.5)
  510 FORMAT (1H1,20X,33HHENYEY STELLAR EVOLUTION PROGRAM )
  511 FORMAT (21X,32HMETHOD OF HENYEY, FORBES + GOULD)
  512 FORMAT (21X,22HAP. J. 139, 306 (1964))
  513 FORMAT (1H0,8H MASS = ,1PE11.4,9H  X(H) = ,0PF7.4,7H  Z =  ,
     1   F7.4)
  514 FORMAT (8H N     =,I5,9H  MODELS=,I5,7H  DTYR=,1PE10.3)
  515 FORMAT (1H0,21HSTATIC INITIAL MODEL ,I4)
  517 FORMAT (8H ALPHA =,F8.3,31H  (MIXING LENGTH/SCALE HEIGHT) )
  520 FORMAT (1H0,5HMODEL,5X,7HAGE(YR),6X,6HDT(YR),3X,2HIT,3X,
     1   6HL/LSUN,5X,6HR/RSUN,7X,4HTEFF,9X,2HTC,7X,4HRHOC,9X,
     2   2HPC,9X,2HXC)
  521 FORMAT (1H ,I4,1P2E12.4,I4,1P7E11.3)
  540 FORMAT (16H0NO CONVERGENCE )
  541 FORMAT (26H0TIME STEP HALVED, DT(S) =,1PE11.3)
      END
C
C     ------------------------------------------------------------------
C     SUBROUTINE START - FIRST APPROXIMATION TO THE CONFIGURATION.
C     THE PAPER (SEC. V) SCALES A PREVIOUS MODEL HOMOLOGOUSLY.
C     HAVING NO PREVIOUS MODEL, THE GENERATING PROGRAM TAKES THE
C     TOTAL RADIUS AND LUMINOSITY FROM CRUDE MASS-RADIUS AND
C     MASS-LUMINOSITY RELATIONS, OBTAINS THE FITTING VALUES FROM
C     THE ENVELOPE INTEGRATION, AND MARCHES A ROUGH MODEL INWARD
C     ZONE BY ZONE WITH THE HYDROSTATIC RELATION AND THE SMALLER
C     OF THE RADIATIVE AND ADIABATIC GRADIENTS.  THE RADIUS RUN
C     IS TAKEN FROM THE MASS-RADIUS SHAPE OF THE EMDEN POLYTROPE
C     N=3 (STANDARD TABULATED VALUES).  THE RESULT NEED ONLY BE
C     GOOD ENOUGH TO START THE NEWTON-RAPHSON PROCESS.
C     ------------------------------------------------------------------
      SUBROUTINE START(TOTM,XHYD0)
      COMMON /GRID/ N,XI(201),EMPT(201),EMH(201),EMPH(201)
      COMMON /VARBL/ R(201),F(201),T(201),Q(201),XH(201)
      COMMON /CONST/ G,SIG,ARAD,RGAS,PI,C256,C4PS,C8PI
      COMMON /STARP/ XM,XMI,ZMET,QHYD
      COMMON /SURF/ RSTAR,XLSTA,DXR,DXL
      DIMENSION XLE(29),PHE(29)
C     EMDEN COORDINATE AND MASS FUNCTION PHI = -XI**2*DTHETA/DXI
C     FOR THE POLYTROPE N=3, AT INTERVALS OF 0.25
      DATA XLE/0.,.25,.50,.75,1.00,1.25,1.50,1.75,2.00,2.25,2.50,
     1   2.75,3.00,3.25,3.50,3.75,4.00,4.25,4.50,4.75,5.00,5.25,
     2   5.50,5.75,6.00,6.25,6.50,6.75,6.89685/
      DATA PHE/0.,.005112,.038710,.119605,.252129,.427603,.629801,
     1   .840957,1.045963,1.234240,1.399805,1.540418,1.656448,
     2   1.749846,1.823360,1.879998,1.922704,1.954176,1.976783,
     3   1.992547,2.003150,2.009969,2.014105,2.016422,2.017579,
     4   2.018063,2.018212,2.018235,2.018235/
      Y=1.-XHYD0-ZMET
      RMU=2.*XHYD0+0.75*Y+0.5*ZMET
C     MASS-RADIUS AND MASS-LUMINOSITY GUESSES (SOLAR UNITS)
      RG=6.96*TOTM**0.9
      XL=3.86E-2*TOTM**3.5
      RSTAR=RG
      XLSTA=XL
C     FITTING VALUES FROM THE ENVELOPE INTEGRATION
      CALL ENVEL(RG,XL,XHYD0,RF,TF,QF)
C     RADIUS AT EACH MESH POINT FROM THE POLYTROPIC MASS-RADIUS
C     SHAPE, RESCALED TO JOIN THE ENVELOPE AT THE FITTING POINT.
C     IN THE FIRST TABLE INTERVAL THE SERIES PHI = XI**3/3 IS
C     USED IN PLACE OF LINEAR INTERPOLATION.
      DO 20 J=1,N
      XF=EMPT(J)/XM
      TARG=XF*2.018235
      DO 12 I=1,28
      II=I
      IF (PHE(I+1).GE.TARG) GO TO 14
   12 CONTINUE
      II=28
   14 IF (II.GT.1) GO TO 16
      XIE=(3.*TARG)**0.3333333
      GO TO 18
   16 DEN=PHE(II+1)-PHE(II)
      FR=0.5
      IF (DEN.GT.1.E-5) FR=(TARG-PHE(II))/DEN
      XIE=XLE(II)+FR*(XLE(II+1)-XLE(II))
   18 R(J)=XIE
   20 CONTINUE
      RN0=R(N)
      DO 22 J=1,N
   22 R(J)=R(J)*(RF/RN0)
      R(1)=0.
      T(N)=TF
      Q(N)=QF
      F(N)=XL
C     MARCH THE PRESSURE AND TEMPERATURE INWARD ZONE BY ZONE
      C64=3./(64.*PI*SIG*G)
      PJ1=RGAS*QF**3*TF*RMU+ARAD*TF**4/3.
      NM1=N-1
      DO 60 JJ=1,NM1
      J=N-JJ
      DELM=EMPT(J+1)-EMPT(J)
      EMM=EMH(J)
      RJ1=R(J+1)
      TJ1=T(J+1)
C     HYDROSTATIC PRESSURE STEP (THE FACTORS ARE STAGED TO AVOID
C     OVERFLOW OF R**4 IN SINGLE PRECISION)
      GS=G*EMM/(RJ1*RJ1)
      P=PJ1+GS*(DELM/(12.566371*RJ1*RJ1))
C     TEMPERATURE STEP WITH THE SMALLER OF THE RADIATIVE AND
C     ADIABATIC GRADIENTS
      CALL OPAC(TJ1,Q(J+1),XHYD0,ZMET,CPS,D1,D2)
      XF=EMM/XM
      XLZ=XL*XF*(2.-XF)
      GRR=C64*CPS*(XLZ/EMM)*(PJ1/TJ1**4)
      GRAD=AMIN1(GRR,0.40)
      T(J)=TJ1*(P/PJ1)**GRAD
C     DENSITY FROM THE GAS PRESSURE
      PG=P-ARAD*T(J)**4/3.
      IF (PG.LT.0.1*P) PG=0.1*P
      RHO=PG/(RGAS*T(J)*RMU)
      Q(J)=RHO**0.3333333
      PJ1=P
   60 CONTINUE
C     PSEUDOFLUX GUESS FROM THE INTEGRATED NUCLEAR ENERGY RELEASE
C     OF THE MARCHED STRUCTURE, SO THAT THE ENERGY EQUATION IS
C     ROUGHLY SATISFIED FROM THE OUTSET.  THE MISMATCH WITH THE
C     LUMINOSITY GUESS AT THE FITTING POINT IS REMOVED BY THE
C     NEWTON-RAPHSON PROCESS.
      XLN=0.
      F(1)=0.
      DO 70 J=2,N
      CALL ENUC(T(J-1),Q(J-1),XHYD0,ZMET,E1,D1,D2)
      CALL ENUC(T(J),Q(J),XHYD0,ZMET,E2,D1,D2)
      XLN=XLN+0.5*(E1+E2)*(EMPT(J)-EMPT(J-1))
      F(J)=XLN/(XI(J)*XI(J))
   70 CONTINUE
      RETURN
      END
C
C     ------------------------------------------------------------------
C     SUBROUTINE SOLVE - ONE CONVERGED MODEL BY THE NEWTON-RAPHSON
C     (HENYEY) PROCESS.  THE LINEARIZED DIFFERENCE EQUATIONS ARE
C     REDUCED ZONE BY ZONE WITH THE RECURSION OF EQ. (44),
C          DELTA-U(J) + ALPHA(J)*DELTA-V(J) + GAMMA(J) = 0,
C     STARTING FROM ALPHA(1) = GAMMA(1) = 0 (CENTRAL CONDITION,
C     EQ. 41).  THE STORED ROWS OF EQ. (46) GIVE THE BACKWARD
C     SUBSTITUTION.  ALL CORRECTIONS ARE CARRIED IN RELATIVE FORM
C     (COLUMNS OF THE JACOBIAN SCALED BY THE CURRENT VALUES) TO
C     CONTROL THE ILL-CONDITIONING NOTED IN THE PAPER.
C     IER = 0 CONVERGED, 1 TOO MANY ITERATIONS, 2 SINGULAR MATRIX.
C     ------------------------------------------------------------------
      SUBROUTINE SOLVE(NIT,IER)
      COMMON /GRID/ N,XI(201),EMPT(201),EMH(201),EMPH(201)
      COMMON /VARBL/ R(201),F(201),T(201),Q(201),XH(201)
      COMMON /OLDT/ QN(201),EN(201),DTINV
      COMMON /THERM/ PP(201),DPT(201),DPQ(201),EE(201),DET(201),
     1   DEQ(201),CK(201),DKT(201),DKQ(201),CPA(201),EP(201),
     2   DEPT(201),DEPQ(201)
      COMMON /HENMT/ AL(2,2,201),GA(2,201),ZE(2,2,201),ET(2,2,201),
     1   BE(2,2,201),TQ(2,201),SU(2,201),SV(2,201),DU(2,201),
     2   DV(2,201)
      COMMON /FLAGS/ ICV(201)
      COMMON /CONST/ G,SIG,ARAD,RGAS,PI,C256,C4PS,C8PI
      COMMON /STARP/ XM,XMI,ZMET,QHYD
      COMMON /CTRL/ CLIM,EPSC,ITMAX,ALFA
      COMMON /SURF/ RSTAR,XLSTA,DXR,DXL
      DIMENSION AA(4,9)
      IER=0
      NM1=N-1
      DMAXP=1.
      DO 200 ITER=1,ITMAX
      CALL PHYSIC
C     LOCATE THE CONVECTIVE ZONES BY THE STABILITY CRITERION
C     (EQ. 27).  THE PLACING OF THESE BOUNDARIES IS THE MOST
C     TROUBLESOME PART OF THE METHOD (SEC. IV OF THE PAPER).  IN
C     PLACE OF THE INTERPOLATION AMONG COMPLETE MODELS (FIG. 1)
C     A SIMPLER DEVICE IS USED HERE - AFTER THE EARLY ITERATIONS
C     A ZONE IS RECLASSIFIED ONLY WHEN THE CRITERION IS EXCEEDED
C     BY A DEFINITE MARGIN, AND THE PATTERN IS FROZEN ENTIRELY
C     ONCE THE ITERATION IS WELL ADVANCED, TO PREVENT AN
C     OSCILLATORY INSTABILITY OF THE BOUNDARY.
      IF (ITER.LE.3) CALL CONVCK(0)
      IF (ITER.GT.3 .AND. ITER.LE.12) CALL CONVCK(1)
C     SCALES FOR THE RELATIVE CORRECTIONS
      FLR=1.E-6*ABS(F(N))
      IF (FLR.LE.0.) FLR=1.
      DO 25 J=1,N
      SU(1,J)=R(J)
      IF (SU(1,J).LE.0.) SU(1,J)=1.
      SU(2,J)=ABS(F(J))
      IF (SU(2,J).LT.FLR) SU(2,J)=FLR
      SV(1,J)=T(J)
      SV(2,J)=Q(J)
   25 CONTINUE
C     CENTRAL BOUNDARY CONDITION, EQ. (41) - DELTA-U(1) = 0
      DO 28 K=1,2
      GA(K,1)=0.
      DO 28 L=1,2
   28 AL(L,K,1)=0.
C
C     FORWARD ELIMINATION OVER THE ZONES
      DO 100 J=1,NM1
      CALL ZONEQ(J,AA)
C     SCALE THE COLUMNS BY THE CURRENT VALUES OF THE VARIABLES
      DO 32 I=1,4
      AA(I,1)=AA(I,1)*SU(1,J)
      AA(I,2)=AA(I,2)*SU(2,J)
      AA(I,3)=AA(I,3)*SV(1,J)
      AA(I,4)=AA(I,4)*SV(2,J)
      AA(I,5)=AA(I,5)*SU(1,J+1)
      AA(I,6)=AA(I,6)*SU(2,J+1)
      AA(I,7)=AA(I,7)*SV(1,J+1)
      AA(I,8)=AA(I,8)*SV(2,J+1)
   32 CONTINUE
C     ELIMINATE DELTA-U(J) BY THE RECURSION, EQ. (44)
      DO 34 I=1,4
      AA(I,9)=AA(I,9)-AA(I,1)*GA(1,J)-AA(I,2)*GA(2,J)
   34 CONTINUE
      DO 36 I=1,4
      DO 36 K=1,2
   36 AA(I,2+K)=AA(I,2+K)-AA(I,1)*AL(1,K,J)-AA(I,2)*AL(2,K,J)
C     NORMALIZE EACH ROW BY ITS LARGEST COEFFICIENT
      DO 44 I=1,4
      BIG=0.
      DO 40 K=3,8
      IF (ABS(AA(I,K)).GT.BIG) BIG=ABS(AA(I,K))
   40 CONTINUE
      IF (BIG.GT.0.) GO TO 42
      IER=2
      WRITE (6,542) J
      RETURN
   42 BIG=1./BIG
      DO 43 K=3,9
   43 AA(I,K)=AA(I,K)*BIG
   44 CONTINUE
C     GAUSSIAN ELIMINATION OF DELTA-V(J) (COLUMNS 3 AND 4) WITH
C     ROW INTERCHANGES
      DO 60 KC=1,2
      IC=KC+2
      IP=KC
      BIG=ABS(AA(KC,IC))
      KP1=KC+1
      DO 46 I=KP1,4
      IF (ABS(AA(I,IC)).LE.BIG) GO TO 46
      BIG=ABS(AA(I,IC))
      IP=I
   46 CONTINUE
      IF (IP.EQ.KC) GO TO 50
      DO 48 K=3,9
      TMP=AA(KC,K)
      AA(KC,K)=AA(IP,K)
      AA(IP,K)=TMP
   48 CONTINUE
   50 IF (ABS(AA(KC,IC)).GT.1.E-12) GO TO 52
      IER=2
      WRITE (6,542) J
      RETURN
   52 DO 56 I=KP1,4
      FAC=AA(I,IC)/AA(KC,IC)
      DO 54 K=IC,9
   54 AA(I,K)=AA(I,K)-FAC*AA(KC,K)
   56 CONTINUE
   60 CONTINUE
C     STORE ROWS 1-2 FOR THE BACKWARD SUBSTITUTION (EQ. 46)
      DO 64 L=1,2
      TQ(L,J)=AA(L,9)
      DO 64 K=1,2
      ZE(L,K,J)=AA(L,2+K)
      ET(L,K,J)=AA(L,4+K)
      BE(L,K,J)=AA(L,6+K)
   64 CONTINUE
C     ROWS 3-4 GIVE ALPHA AND GAMMA AT J+1 (EQ. 45)
      C11=AA(3,5)
      C12=AA(3,6)
      C21=AA(4,5)
      C22=AA(4,6)
      DET2=C11*C22-C12*C21
      IF (ABS(DET2).GT.1.E-20) GO TO 66
      IER=2
      WRITE (6,542) J
      RETURN
   66 AL(1,1,J+1)=(C22*AA(3,7)-C12*AA(4,7))/DET2
      AL(1,2,J+1)=(C22*AA(3,8)-C12*AA(4,8))/DET2
      AL(2,1,J+1)=(C11*AA(4,7)-C21*AA(3,7))/DET2
      AL(2,2,J+1)=(C11*AA(4,8)-C21*AA(3,8))/DET2
      GA(1,J+1)=(C22*AA(3,9)-C12*AA(4,9))/DET2
      GA(2,J+1)=(C11*AA(4,9)-C21*AA(3,9))/DET2
  100 CONTINUE
C
C     OUTER BOUNDARY - THE FITTING CONDITIONS, EQS. (37)-(38) AND
C     (42)-(43).  THE OUTER ENVELOPE (MASS FRACTION DELS) IS
C     INTEGRATED SEPARATELY AS A FUNCTION OF THE TOTAL RADIUS AND
C     LUMINOSITY, GIVING THE FITTED QUANTITIES OF EQS. (30)-(33).
C     THE PAPER INTERPOLATES AMONG FOUR STORED ATMOSPHERE CASES
C     (FIG. 4) - HERE THE INTEGRATION IS SIMPLY REPEATED AND THE
C     PARTIAL DERIVATIVES ARE OBTAINED BY DIFFERENCING.
      CALL ENVEL(RSTAR,XLSTA,XH(N),RF0,TF0,QF0)
      DH=0.02
      CALL ENVEL(RSTAR*(1.+DH),XLSTA,XH(N),RF1,TF1,QF1)
      CALL ENVEL(RSTAR,XLSTA*(1.+DH),XH(N),RF2,TF2,QF2)
      FJ11=(RF1-RF0)/DH
      FJ12=(RF2-RF0)/DH
      FJ31=(TF1-TF0)/DH
      FJ32=(TF2-TF0)/DH
      FJ41=(QF1-QF0)/DH
      FJ42=(QF2-QF0)/DH
      SR1=R(N)-RF0
      SR2=F(N)-XLSTA
      SR3=T(N)-TF0
      SR4=Q(N)-QF0
      S1=SU(1,N)
      S2=SU(2,N)
      S3=SV(1,N)
      S4=SV(2,N)
C     SUBSTITUTE THE LINEARIZED FITTING RELATIONS INTO THE
C     RECURSION (44) AT J = N AND SOLVE FOR THE RELATIVE CHANGES
C     OF THE TOTAL RADIUS AND LUMINOSITY
      A11=FJ11/S1+AL(1,1,N)*FJ31/S3+AL(1,2,N)*FJ41/S4
      A12=FJ12/S1+AL(1,1,N)*FJ32/S3+AL(1,2,N)*FJ42/S4
      B1=SR1/S1+AL(1,1,N)*SR3/S3+AL(1,2,N)*SR4/S4-GA(1,N)
      A21=AL(2,1,N)*FJ31/S3+AL(2,2,N)*FJ41/S4
      A22=XLSTA/S2+AL(2,1,N)*FJ32/S3+AL(2,2,N)*FJ42/S4
      B2=SR2/S2+AL(2,1,N)*SR3/S3+AL(2,2,N)*SR4/S4-GA(2,N)
      DET2=A11*A22-A12*A21
      IF (ABS(DET2).GT.1.E-20) GO TO 120
      IER=2
      WRITE (6,542) N
      RETURN
  120 DXR=(B1*A22-B2*A12)/DET2
      DXL=(B2*A11-B1*A21)/DET2
      DV(1,N)=(FJ31*DXR+FJ32*DXL-SR3)/S3
      DV(2,N)=(FJ41*DXR+FJ42*DXL-SR4)/S4
      DU(1,N)=(FJ11*DXR+FJ12*DXL-SR1)/S1
      DU(2,N)=(XLSTA*DXL-SR2)/S2
C
C     BACKWARD SUBSTITUTION, EQS. (46) AND (44), FOR DECREASING J
      DO 140 JJ=1,NM1
      J=N-JJ
      T1=TQ(1,J)+ET(1,1,J)*DU(1,J+1)+ET(1,2,J)*DU(2,J+1)
     1   +BE(1,1,J)*DV(1,J+1)+BE(1,2,J)*DV(2,J+1)
      T2=TQ(2,J)+ET(2,1,J)*DU(1,J+1)+ET(2,2,J)*DU(2,J+1)
     1   +BE(2,1,J)*DV(1,J+1)+BE(2,2,J)*DV(2,J+1)
      IF (ABS(ZE(2,2,J)).GT.1.E-20 .AND. ABS(ZE(1,1,J)).GT.1.E-20)
     1   GO TO 130
      IER=2
      WRITE (6,542) J
      RETURN
  130 DV(2,J)=-T2/ZE(2,2,J)
      DV(1,J)=-(T1+ZE(1,2,J)*DV(2,J))/ZE(1,1,J)
      DU(1,J)=-AL(1,1,J)*DV(1,J)-AL(1,2,J)*DV(2,J)-GA(1,J)
      DU(2,J)=-AL(2,1,J)*DV(1,J)-AL(2,2,J)*DV(2,J)-GA(2,J)
  140 CONTINUE
C
C     LARGEST RELATIVE CORRECTION.  FOLLOWING THE PAPER (SEC. V),
C     DELTA-F/F IS EXAMINED ONLY AT THE SURFACE, SINCE F MAY PASS
C     THROUGH ZERO AT INTERIOR POINTS.
      DMAX=0.
      DO 150 J=1,N
      IF (J.GT.1 .AND. ABS(DU(1,J)).GT.DMAX) DMAX=ABS(DU(1,J))
      IF (ABS(DV(1,J)).GT.DMAX) DMAX=ABS(DV(1,J))
      IF (ABS(DV(2,J)).GT.DMAX) DMAX=ABS(DV(2,J))
  150 CONTINUE
      IF (ABS(DU(2,N)).GT.DMAX) DMAX=ABS(DU(2,N))
      IF (ABS(DXR).GT.DMAX) DMAX=ABS(DXR)
      IF (ABS(DXL).GT.DMAX) DMAX=ABS(DXL)
C     LIMIT THE INCREMENTS (SEC. V OF THE PAPER)
      DAMP=1.
      IF (DMAX.GT.CLIM) DAMP=CLIM/DMAX
      DO 160 J=1,N
      R(J)=R(J)+DAMP*SU(1,J)*DU(1,J)
      F(J)=F(J)+DAMP*SU(2,J)*DU(2,J)
      T(J)=T(J)+DAMP*SV(1,J)*DV(1,J)
      Q(J)=Q(J)+DAMP*SV(2,J)*DV(2,J)
  160 CONTINUE
      RSTAR=RSTAR*(1.+DAMP*DXR)
      XLSTA=XLSTA*(1.+DAMP*DXL)
      WRITE (6,530) ITER,DMAX,DAMP
      DMAXP=DMAX
      IF (DMAX.LT.EPSC) GO TO 210
      IF (ITER.GE.20 .AND. DMAX.LT.20.*EPSC) GO TO 210
  200 CONTINUE
      IER=1
      NIT=ITMAX
      RETURN
  210 NIT=ITER
      CALL PHYSIC
      RETURN
  530 FORMAT (6H ITER=,I3,14H  MAX CORRECT=,1PE10.2,7H  DAMP=,
     1   0PF6.3)
  542 FORMAT (25H0SINGULAR MATRIX AT ZONE ,I4)
      END
C
C     ------------------------------------------------------------------
C     SUBROUTINE PHYSIC - THE MATERIAL FUNCTIONS P, E, K, EPSILON
C     AND THEIR PARTIAL DERIVATIVES WITH RESPECT TO T AND Q AT
C     EVERY MESH POINT (SECOND BOX OF FIG. 2).
C     ------------------------------------------------------------------
      SUBROUTINE PHYSIC
      COMMON /GRID/ N,XI(201),EMPT(201),EMH(201),EMPH(201)
      COMMON /VARBL/ R(201),F(201),T(201),Q(201),XH(201)
      COMMON /THERM/ PP(201),DPT(201),DPQ(201),EE(201),DET(201),
     1   DEQ(201),CK(201),DKT(201),DKQ(201),CPA(201),EP(201),
     2   DEPT(201),DEPQ(201)
      COMMON /CONST/ G,SIG,ARAD,RGAS,PI,C256,C4PS,C8PI
      COMMON /STARP/ XM,XMI,ZMET,QHYD
      DO 10 J=1,N
      CALL STATE(T(J),Q(J),XH(J),ZMET,PP(J),DPT(J),DPQ(J),EE(J),
     1   DET(J),DEQ(J))
      CALL OPAC(T(J),Q(J),XH(J),ZMET,CPA(J),DCT,DCQ)
C     THE MODIFIED OPACITY VARIABLE K OF EQ. (11)
      CK(J)=3.*CPA(J)*PP(J)**3/(C256*T(J)**3)
      DKT(J)=CK(J)*(DCT/CPA(J)+3.*DPT(J)/PP(J)-3./T(J))
      DKQ(J)=CK(J)*(DCQ/CPA(J)+3.*DPQ(J)/PP(J))
      CALL ENUC(T(J),Q(J),XH(J),ZMET,EP(J),DEPT(J),DEPQ(J))
   10 CONTINUE
      RETURN
      END
C
C     ------------------------------------------------------------------
C     SUBROUTINE CONVCK - STABILITY AGAINST CONVECTION FOR EACH
C     ZONE (EQ. 27).  THE ZONE IS CONVECTIVE WHEN THE RADIATIVE
C     GRADIENT DLOG(T)/DLOG(P) EXCEEDS THE ADIABATIC VALUE 0.40.
C     WHERE CONVECTIVE, THE ADIABATIC CONDITION (EQ. 26) REPLACES
C     THE RADIATIVE CONDITION (EQ. 25) IN THE DIFFERENCE SYSTEM.
C     FOR MODE = 1 A ZONE IS RECLASSIFIED ONLY WHEN THE CRITERION
C     IS PASSED BY A TEN PER CENT MARGIN (HYSTERESIS), WHICH
C     SUPPRESSES THE FLUTTER OF THE CONVECTIVE BOUNDARIES DURING
C     THE ITERATION.
C     ------------------------------------------------------------------
      SUBROUTINE CONVCK(MODE)
      COMMON /GRID/ N,XI(201),EMPT(201),EMH(201),EMPH(201)
      COMMON /VARBL/ R(201),F(201),T(201),Q(201),XH(201)
      COMMON /THERM/ PP(201),DPT(201),DPQ(201),EE(201),DET(201),
     1   DEQ(201),CK(201),DKT(201),DKQ(201),CPA(201),EP(201),
     2   DEPT(201),DEPQ(201)
      COMMON /FLAGS/ ICV(201)
      COMMON /CONST/ G,SIG,ARAD,RGAS,PI,C256,C4PS,C8PI
      COMMON /STARP/ XM,XMI,ZMET,QHYD
      NM1=N-1
      C64=3./(64.*PI*SIG*G)
      DO 10 J=1,NM1
      TB=0.5*(T(J)+T(J+1))
      PB=(0.5*(PP(J)+PP(J+1)))**4
      CB=0.5*(CPA(J)+CPA(J+1))
      XB=0.5*(XI(J)+XI(J+1))
      FB=0.5*(F(J)+F(J+1))
      XLB=XB*XB*FB
      GR=C64*CB*(XLB/EMH(J))*(PB/TB**4)
      IF (MODE.EQ.1) GO TO 5
      ICV(J)=0
      IF (GR.GT.0.40) ICV(J)=1
      GO TO 10
    5 IF (GR.GT.0.44) ICV(J)=1
      IF (GR.LT.0.36) ICV(J)=0
   10 CONTINUE
      RETURN
      END
C
C     ------------------------------------------------------------------
C     SUBROUTINE ZONEQ - THE FOUR DIFFERENCE EQUATIONS OF THE ZONE
C     BETWEEN POINTS J AND J+1, EQS. (22), (23), (24), AND (25) OR
C     (26), WITH THEIR PARTIAL DERIVATIVES (THE TENSORS OF EQS.
C     39-40).  AA(I,1-8) = DERIVATIVES WITH RESPECT TO R,F,T,Q AT
C     J AND AT J+1.  AA(I,9) = THE RESIDUAL.  THE DERIVATIVES WITH
C     RESPECT TO T AND Q INCLUDE THE IMPLICIT VARIATION THROUGH
C     P(T,Q), E(T,Q), K(T,Q), AND EPSILON(T,Q).
C     ------------------------------------------------------------------
      SUBROUTINE ZONEQ(J,AA)
      DIMENSION AA(4,9)
      COMMON /GRID/ N,XI(201),EMPT(201),EMH(201),EMPH(201)
      COMMON /VARBL/ R(201),F(201),T(201),Q(201),XH(201)
      COMMON /OLDT/ QN(201),EN(201),DTINV
      COMMON /THERM/ PP(201),DPT(201),DPQ(201),EE(201),DET(201),
     1   DEQ(201),CK(201),DKT(201),DKQ(201),CPA(201),EP(201),
     2   DEPT(201),DEPQ(201)
      COMMON /FLAGS/ ICV(201)
      COMMON /CONST/ G,SIG,ARAD,RGAS,PI,C256,C4PS,C8PI
      COMMON /STARP/ XM,XMI,ZMET,QHYD
      J1=J
      J2=J+1
      X1=XI(J1)
      X2=XI(J2)
      XS=X1+X2
      XD=X2-X1
      RS=R(J1)+R(J2)
      RD=R(J2)-R(J1)
      PS=PP(J1)+PP(J2)
      PD=PP(J2)-PP(J1)
      QS=Q(J1)+Q(J2)
      QD=Q(J2)-Q(J1)
      DO 10 I=1,4
      DO 10 K=1,9
   10 AA(I,K)=0.
C
C     EQUATION (22) - HYDROSTATIC EQUILIBRIUM
      WR=G*EMH(J)*(QS/PS)**3/(RS*RS)
      W=WR*RD
      AA(1,1)=-WR-2.*W/RS
      AA(1,5)=WR-2.*W/RS
      CP1=-1.-3.*W/PS
      CP2=1.-3.*W/PS
      AA(1,3)=CP1*DPT(J1)
      AA(1,4)=CP1*DPQ(J1)+3.*W/QS
      AA(1,7)=CP2*DPT(J2)
      AA(1,8)=CP2*DPQ(J2)+3.*W/QS
      AA(1,9)=PD+W
C
C     EQUATION (23) - MASS CONTINUITY
      QS3=QS**3
      AA(2,1)=QS3*RS*(RS-2.*RD)
      AA(2,5)=-QS3*RS*(RS+2.*RD)
      AA(2,4)=-3.*QS*QS*RS*RS*RD
      AA(2,8)=AA(2,4)
      AA(2,9)=C8PI*EMPH(J)*XD-QS3*RS*RS*RD
C
C     EQUATION (24) - ENERGY BALANCE WITH BACKWARD TIME
C     DIFFERENCES.  THE NUCLEAR RATE ENTERS AS THE GEOMETRIC MEAN
C     OF THE VALUES AT THE TWO POINTS.
      A4=3.*(PS/QS)**4
      A4P=4.*A4/PS
      A4Q=4.*A4/QS
      E1=EP(J1)
      E2=EP(J2)
      GE=0.
      GT1=0.
      GQ1=0.
      GT2=0.
      GQ2=0.
      IF (E1.LE.1.E-15 .OR. E2.LE.1.E-15) GO TO 20
      GE=2.*SQRT(E1*E2)
      GT1=0.5*GE*DEPT(J1)/E1
      GQ1=0.5*GE*DEPQ(J1)/E1
      GT2=0.5*GE*DEPT(J2)/E2
      GQ2=0.5*GE*DEPQ(J2)/E2
   20 CONTINUE
      DQT=Q(J1)+Q(J2)-QN(J1)-QN(J2)
      BR=GE-(EE(J1)+EE(J2)-EN(J1)-EN(J2))*DTINV+A4*DQT*DTINV
      CM=2.*EMPH(J)*XD
      BT1=GT1-DET(J1)*DTINV+A4P*DPT(J1)*DQT*DTINV
      BQ1=GQ1-DEQ(J1)*DTINV+(A4P*DPQ(J1)-A4Q)*DQT*DTINV+A4*DTINV
      BT2=GT2-DET(J2)*DTINV+A4P*DPT(J2)*DQT*DTINV
      BQ2=GQ2-DEQ(J2)*DTINV+(A4P*DPQ(J2)-A4Q)*DQT*DTINV+A4*DTINV
      AA(3,2)=XS*(X2-3.*X1)
      AA(3,6)=XS*(3.*X2-X1)
      AA(3,3)=-CM*BT1
      AA(3,4)=-CM*BQ1
      AA(3,7)=-CM*BT2
      AA(3,8)=-CM*BQ2
      AA(3,9)=F(J2)*XS*(3.*X2-X1)+F(J1)*XS*(X2-3.*X1)-CM*BR
C
      IF (ICV(J).EQ.1) GO TO 40
C
C     EQUATION (25) - RADIATIVE TRANSPORT
      CKS=CK(J1)+CK(J2)
      FS=F(J1)+F(J2)
      CW=XS*XS/EMH(J)
      CWF=CW*FS
      AA(4,2)=-CKS*CW*PD
      AA(4,6)=AA(4,2)
      AA(4,3)=-1.-CWF*(DKT(J1)*PD-CKS*DPT(J1))
      AA(4,7)=1.-CWF*(DKT(J2)*PD+CKS*DPT(J2))
      AA(4,4)=-CWF*(DKQ(J1)*PD-CKS*DPQ(J1))
      AA(4,8)=-CWF*(DKQ(J2)*PD+CKS*DPQ(J2))
      AA(4,9)=T(J2)-T(J1)-CKS*CWF*PD
      GO TO 50
C
C     EQUATION (26) - CONVECTIVE (ADIABATIC) TRANSPORT
   40 AA(4,3)=-DET(J1)-A4P*DPT(J1)*QD
      AA(4,7)=DET(J2)-A4P*DPT(J2)*QD
      AA(4,4)=-DEQ(J1)-(A4P*DPQ(J1)-A4Q)*QD+A4
      AA(4,8)=DEQ(J2)-(A4P*DPQ(J2)-A4Q)*QD-A4
      AA(4,9)=EE(J2)-EE(J1)-A4*QD
   50 RETURN
      END
C
C     ------------------------------------------------------------------
C     SUBROUTINE ENVEL - THE OUTER-ZONE (ENVELOPE) INTEGRATION,
C     TAKING THE PLACE OF THE ATMOSPHERE PROGRAM OF M. S. VARDYA
C     REFERRED TO IN THE PAPER.  GIVEN THE TOTAL RADIUS RS AND
C     LUMINOSITY XLS, THE FLUX TEMPERATURE FOLLOWS FROM
C          TF**4 = L/(4*PI*SIGMA*R**2)
C     (HVB 1965, EQ. 8).  THE OUTERMOST LAYERS ARE IN RADIATIVE
C     EQUILIBRIUM AND FOLLOW THE BLANKETED T-TAU RELATION OF
C     HENYEY, VARDYA + BODENHEIMER (1965, AP. J. 142, 841),
C     EQ. (10) WITH THE COEFFICIENTS OF EQS. (11)-(12) AND THE
C     METAL SCALING ZETA OF EQ. (9) - SEE SUBROUTINE TTAU.  THIS
C     LAYER IS INTEGRATED IN OPTICAL DEPTH FROM TAU = 0.01 WITH
C     THE HYDROSTATIC RELATION DP = (G/KAPPA)*DTAU, DOWN TO THE
C     ONSET OF CONVECTION (WHERE THE GRADIENT ALONG THE RELATION
C     FIRST REACHES THE ADIABATIC ONE) OR TO TAU NEAR 50.  FROM
C     THERE THE ENVELOPE (MASS FRACTION DELS OF THE STAR, WITH
C     L TAKEN CONSTANT AND THE TIME TERMS NEGLECTED) IS
C     INTEGRATED INWARD ON A LOGARITHMIC COLUMN-MASS SCALE WITH
C     THE HYDROSTATIC RELATION AND THE SMALLER OF THE RADIATIVE
C     AND MIXING-LENGTH GRADIENTS.  (THE FLUX CORRECTION F OF HVB
C     EQ. 26 IS NEAR UNITY AT THE HANDOVER DEPTH AND IS OMITTED
C     BELOW IT.)  RETURNED ARE THE FITTED VALUES OF EQS. (30),
C     (32), (33) AT THE OUTERMOST INTERIOR POINT - RF (RADIUS),
C     TF (TEMPERATURE), QF (CUBE ROOT OF DENSITY).
C     ------------------------------------------------------------------
      SUBROUTINE ENVEL(RS,XLS,XSU,RF,TF,QF)
      COMMON /CONST/ G,SIG,ARAD,RGAS,PI,C256,C4PS,C8PI
      COMMON /STARP/ XM,XMI,ZMET,QHYD
      COMMON /CTRL/ CLIM,EPSC,ITMAX,ALFA
      TE=SQRT(SQRT(XLS/(C4PS*RS*RS)))
      TE4=TE**4
C     BLANKETING COEFFICIENTS, HVB (1965) EQS. (9), (11), (12).
C     THE PARENTHETICAL (1.E-4*TF - 1.1) IS HELD AT 0.4 ABOVE
C     15000 K, AS PRESCRIBED.  THE SOLAR METAL-TO-HYDROGEN RATIO
C     OF EQ. (9) IS TAKEN AT X = 0.708, Z = 0.020.
      T4K=1.E3*TE
      BSE=T4K-1.1
      IF (BSE.GT.0.4) BSE=0.4
      B4=BSE*BSE*BSE*BSE
      ABLK=(0.6379*B4+0.02565)*TE4
      CBLK=1./(5.465-2.087*T4K)
      IF (T4K.GE.0.98) CBLK=1./(2.68*T4K+0.79)
      BBLK=(0.5146*B4+0.4605-CBLK)*TE4
      ZETA=SQRT(35.4*ZMET/XSU)
C     STARTING POINT OF THE RADIATIVE LAYER, P = G*TAU/KAPPA,
C     WITH THE DENSITY FROM A SHORT FIXED-POINT ITERATION
      TAU=0.01
      CALL TTAU(TAU,TE4,ZETA,ABLK,BBLK,T4X,DT4)
      TX=SQRT(SQRT(T4X))
      R3=RS**3
      GS=G*XM/(RS*RS)
      RHO=1.E-9
      DO 10 I=1,25
      CALL OPAC(TX,RHO**0.3333333,XSU,ZMET,CPS,D1,D2)
      P=GS*TAU/CPS
      PG=P-ARAD*T4X/3.
      IF (PG.LT.0.1*P) PG=0.1*P
      CALL SAHA(PG,TX,XSU,ZMET,RHN,CPD,DELD,GRADA)
      RHO=SQRT(RHO*RHN)
   10 CONTINUE
      XMU=12.566371*RS*RS*P/GS
C     MARCH OF THE RADIATIVE LAYER - FIFTEEN LOGARITHMIC STEPS
C     PER DECADE OF OPTICAL DEPTH, EACH WITH ONE CORRECTOR PASS
C     FOR THE STEEP H-MINUS OPACITY.  TAUP IS THE EFFECTIVE
C     (SPHERICAL) DEPTH OF HVB EQ. (7).
      TAUP=TAU
      DO 20 K=1,56
      TAUN=TAU*1.1659144
      DTAU=TAUN-TAU
      R23=R3**0.6666667
      GLOC=G*XM/R23
      SPH=RS*RS/R23
      CALL OPAC(TX,RHO**0.3333333,XSU,ZMET,CPS,D1,D2)
      TAUPN=TAUP+SPH*DTAU
      CALL TTAU(TAUPN,TE4,ZETA,ABLK,BBLK,T4N,DT4)
      TN=SQRT(SQRT(T4N))
      PN=P+GLOC*DTAU/CPS
      PG=PN-ARAD*T4N/3.
      IF (PG.LT.0.1*PN) PG=0.1*PN
      CALL SAHA(PG,TN,XSU,ZMET,RHN,CPD,DELD,GRADA)
      CALL OPAC(TN,RHN**0.3333333,XSU,ZMET,CPN,D1,D2)
      PN=P+GLOC*DTAU*0.5*(1./CPS+1./CPN)
      PG=PN-ARAD*T4N/3.
      IF (PG.LT.0.1*PN) PG=0.1*PN
      CALL SAHA(PG,TN,XSU,ZMET,RHN,CPD,DELD,GRADA)
C     ONSET OF CONVECTION - THE GRADIENT ALONG THE RELATION,
C     D LN T / D LN P = P*KAPPA*(R0/R)**2*(DT4/DTAU)/(4*T**4*G),
C     TESTED AGAINST THE ADIABATIC GRADIENT
      GRREL=PN*CPN*SPH*DT4/(4.*T4N*GLOC)
      IF (GRREL.GE.GRADA) GO TO 25
      DR=DTAU/(CPN*RHN)
      XMU=XMU+12.566371*R23*RHN*DR
      R3=R3-3.*R23*DR
      P=PN
      TX=TN
      RHO=RHN
      TAU=TAUN
      TAUP=TAUPN
   20 CONTINUE
   25 CONTINUE
      C64=3./(64.*PI*SIG*G)
      DELME=XM-XMI
      NE=140
C     INWARD MARCH ON A LOGARITHMIC SCALE OF EXTERIOR COLUMN
C     MASS, TAKEN UP AT THE COLUMN MASS REACHED BY THE RADIATIVE
C     LAYER
      XL0=ALOG10(XMU/DELME)
      IF (XL0.LT.-9.) XL0=-9.
      IF (XL0.GT.-0.1) GO TO 45
      DO 40 K=1,NE
      XMUN=DELME*10.**(XL0*(1.-FLOAT(K)/FLOAT(NE)))
      DMU=XMUN-XMU
C     HYDROSTATIC STEP (STAGED TO AVOID OVERFLOW OF R**4)
      T1=G*XM/R3
      DP=T1*(DMU/(12.566371*R3**0.3333333))
C     THERMODYNAMIC QUANTITIES OF THE LAYER FROM THE IONIZATION
C     EQUILIBRIUM (HVB 1965, SEC. II), REPLACING THE FULLY
C     IONIZED IDEAL GAS
      PG=P-ARAD*TX**4/3.
      IF (PG.LT.0.1*P) PG=0.1*P
      CALL SAHA(PG,TX,XSU,ZMET,RHO,CPD,DELD,GRADA)
      CALL OPAC(TX,RHO**0.3333333,XSU,ZMET,CPS,D1,D2)
      GRR=C64*CPS*(XLS/XM)*(P/TX**4)
C     WHERE THE LAYER IS UNSTABLE, THE GRADIENT COMES FROM THE
C     BOEHM-VITENSE (1958) MIXING-LENGTH THEORY WITH THE RATIO
C     ALPHA OF MIXING LENGTH TO PRESSURE SCALE HEIGHT AS THE
C     FREE PARAMETER (P. BODENHEIMER RECALLS PRECISELY THIS
C     TREATMENT IN THE VARDYA ATMOSPHERE PROGRAM).  THE CUBIC IN
C     XI = SQRT(GRAD - GRADAD + U**2) IS SOLVED BY BISECTION -
C        (XI-U)**3 + (8U/9)(XI**2 - U**2 - W) = 0,
C        W = GRADRAD - GRADAD,
C        U = 12 SIGMA T**3 SQRT(8 HP/GEE) / (CP RHO**2 KAPPA L**2)
      GRAD=GRR
      IF (GRR.LE.GRADA) GO TO 34
      GEE=G*XM/R3**0.6666667
      HP=P/(RHO*GEE)
      EL=ALFA*HP
      UMLT=12.*SIG*TX**3*SQRT(8.*HP/(GEE*DELD))/(CPD*RHO*RHO*CPS
     1   *EL*EL)
      WMLT=GRR-GRADA
      X1B=UMLT
      X2B=SQRT(WMLT+UMLT*UMLT)
      DO 32 IB=1,45
      XMB=0.5*(X1B+X2B)
      FCB=(XMB-UMLT)**3+(8.*UMLT/9.)*(XMB*XMB-UMLT*UMLT-WMLT)
      IF (FCB.GT.0.) X2B=XMB
      IF (FCB.LE.0.) X1B=XMB
   32 CONTINUE
      GRAD=GRADA+XMB*XMB-UMLT*UMLT
   34 CONTINUE
      PN=P+DP
      TX=TX*(PN/P)**GRAD
      P=PN
      R3=R3-DMU/(4.1887902*RHO)
      R3MIN=0.001*RS**3
      IF (R3.LT.R3MIN) R3=R3MIN
      XMU=XMUN
   40 CONTINUE
   45 CONTINUE
      RF=R3**0.3333333
      TF=TX
      QF=RHO**0.3333333
      RETURN
      END
C
C     ------------------------------------------------------------------
C     SUBROUTINE TTAU - THE BLANKETED RADIATIVE TEMPERATURE LAW OF
C     HENYEY, VARDYA + BODENHEIMER (1965), EQ. (10),
C        T**4 = (3/4)*TF**4*(TAU + 0.727 - 0.1406*EXP(-2.54*TAU))
C               + ZETA*(A - B*EXP(-30*TAU)),
C     AND ITS DERIVATIVE WITH RESPECT TO THE (EFFECTIVE) OPTICAL
C     DEPTH.  THE EXPONENTIALS ARE GUARDED AGAINST UNDERFLOW AND
C     THE FOURTH POWER OF THE TEMPERATURE IS KEPT ABOVE A SMALL
C     FLOOR.
C     ------------------------------------------------------------------
      SUBROUTINE TTAU(TAUP,TE4,ZETA,ABLK,BBLK,T4X,DT4)
      EX1=0.
      ARG=-2.54*TAUP
      IF (ARG.GT.-80.) EX1=EXP(ARG)
      EX2=0.
      ARG=-30.*TAUP
      IF (ARG.GT.-80.) EX2=EXP(ARG)
      T4X=0.75*TE4*(TAUP+0.727-0.1406*EX1)+ZETA*(ABLK-BBLK*EX2)
      IF (T4X.LT.0.05*TE4) T4X=0.05*TE4
      DT4=0.75*TE4*(1.+0.3571240*EX1)+30.*ZETA*BBLK*EX2
      RETURN
      END
C
C     ------------------------------------------------------------------
C     SUBROUTINE SAHA - IONIZATION EQUILIBRIUM AND THERMODYNAMICS
C     OF THE ENVELOPE MATERIAL, AFTER THE TREATMENT OF VARDYA
C     DESCRIBED IN HENYEY, VARDYA + BODENHEIMER (1965, AP. J.
C     142, 841, SEC. II).  HYDROGEN (H, H+), HELIUM (HE, HE+,
C     HE++), AND A SINGLE REPRESENTATIVE METAL (FIRST IONIZATION
C     7.5 EV, MEAN WEIGHT 24) SUPPLY THE ELECTRON PRESSURE.
C     MOLECULES, THE H- STATES OF THE FULL VARDYA TREATMENT, AND
C     THE TURBULENT PRESSURE OF HVB (WHICH PROVED CONTROVERSIAL)
C     ARE OMITTED.  RETURNED ARE THE DENSITY, THE SPECIFIC HEAT
C     AT CONSTANT PRESSURE, THE EXPANSION COEFFICIENT
C     DELTA = -DLNRHO/DLNT AT CONSTANT P, AND THE ADIABATIC
C     GRADIENT, THE LAST THREE BY DIFFERENCES OF THE EQUILIBRIUM
C     AT NEIGHBORING STATES.
C     ------------------------------------------------------------------
      SUBROUTINE SAHA(PG,TT,X,Z,RHO,CP,DELTA,GRADA)
      COMMON /CONST/ G,SIG,ARAD,RGAS,PI,C256,C4PS,C8PI
      EPS=0.02
      CALL SAHA1(PG,TT,X,Z,RHO,H0)
      CALL SAHA1(PG,TT*(1.+EPS),X,Z,RH1,H1)
      DELTA=-(ALOG(RH1)-ALOG(RHO))/EPS
      IF (DELTA.LT.0.1) DELTA=0.1
      CP=(H1-H0)/(EPS*TT)
      GRADA=PG*DELTA/(TT*RHO*CP)
      IF (GRADA.LT.0.03) GRADA=0.03
      IF (GRADA.GT.0.42) GRADA=0.42
      RETURN
      END
C
C     ------------------------------------------------------------------
C     SUBROUTINE SAHA1 - ONE SOLUTION OF THE IONIZATION
C     EQUILIBRIUM AT GIVEN GAS PRESSURE AND TEMPERATURE.  THE
C     ELECTRON PRESSURE IS FOUND BY A DAMPED FIXED-POINT
C     ITERATION OF FIXED LENGTH, SO THAT THE MAPPING REMAINS
C     SMOOTH IN ITS ARGUMENTS (SEE THE REMARKS ON CONTINUITY IN
C     SEC. V OF THE 1964 PAPER).  THE SAHA FUNCTIONS ARE IN THE
C     PRESSURE FORM, PHI = 0.6665*(U1/U0)*T**2.5*EXP(-CHI/KT),
C     C.G.S., AND THE ROUTINE CONVERTS FROM AND TO THE SCALED
C     UNITS OF THE REST OF THE PROGRAM.  RETURNED ARE THE
C     DENSITY AND THE SPECIFIC ENTHALPY (TRANSLATION PLUS
C     IONIZATION).
C     ------------------------------------------------------------------
      SUBROUTINE SAHA1(PG,TT,X,Z,RHO,HH)
      TC=1.E7*TT
      PC=1.E10*PG
      Y=1.-X-Z
      ANH=X/1.008
      ANHE=Y/4.003
      ANM=Z/24.
      ANI=ANH+ANHE+ANM
      T25=TC*TC*SQRT(TC)
      PH=0.
      ARG=-157800./TC
      IF (ARG.GT.-80.) PH=0.3333*T25*EXP(ARG)
      PB1=0.
      ARG=-285300./TC
      IF (ARG.GT.-80.) PB1=1.333*T25*EXP(ARG)
      PB2=0.
      ARG=-631500./TC
      IF (ARG.GT.-80.) PB2=0.3333*T25*EXP(ARG)
      PM=0.
      ARG=-87000./TC
      IF (ARG.GT.-80.) PM=0.6665*T25*EXP(ARG)
      PE=0.01*PC
      DO 20 IT=1,60
      FH=PH/(PH+PE)
      FM=PM/(PM+PE)
      R1=AMIN1(PB1/PE,1.E15)
      R2=AMIN1(PB2/PE,1.E15)
      D=1.+R1+R1*R2
      Y1=R1/D
      Y2=R1*R2/D
      ANE=ANH*FH+ANHE*(Y1+2.*Y2)+ANM*FM
      PEN=PC*ANE/(ANI+ANE)
      IF (PEN.LT.1.E-25) PEN=1.E-25
      PE=SQRT(PE*PEN)
   20 CONTINUE
      RHO=PC/(8.25E7*TC*(ANI+ANE))
      HH=(2.5*8.25E7*TC*(ANI+ANE)+9.648E11*(ANH*FH*13.60
     1   +ANHE*(Y1*24.59+Y2*79.01)+ANM*FM*7.5))*1.E-10
      RETURN
      END
C
C     ------------------------------------------------------------------
C     SUBROUTINE STATE - EQUATION OF STATE OF THE FULLY IONIZED
C     INTERIOR, AFTER APPENDIX A OF BODENHEIMER, FORBES, GOULD +
C     HENYEY (1965, AP. J. 141, 1019).  IONS AND RADIATION ARE
C     IDEAL.  THE ELECTRONS CARRY THE DEGENERACY CORRECTION H(G)
C     OF EQ. (A7), WITH  G = H**3 N(E) / (2 (2 PI M K T)**3/2),
C     AND THE RELATIVISTIC FACTOR K(X) OF EQ. (A12) -
C        P(E) = N(E) K T H / K ,   E(E) = 3 N(E) K T H / (1 + K)
C     (EQS. A13, A14).  PARTIAL IONIZATION IS NOT NEEDED HERE (THE
C     ENVELOPE HAS ITS OWN TREATMENT); THE PRESSURE-IONIZATION
C     ESTIMATE (A1) FOR THE METALS IS OMITTED, THEIR ELECTRONS
C     BEING TAKEN AS FREE.  THE MODIFIED VARIABLE P = P**(1/4) AND
C     THE DERIVATIVES FOR THE JACOBIAN ARE FORMED FROM CENTERED
C     DIFFERENCES OF THE EVALUATOR STATEV.
C     ------------------------------------------------------------------
      SUBROUTINE STATE(TT,QQ,X,Z,PPX,DPTX,DPQX,EX,DETX,DEQX)
      DEL=0.02
      CALL STATEV(TT,QQ,X,Z,P0,E0)
      CALL STATEV(TT*(1.+DEL),QQ,X,Z,P1,E1)
      CALL STATEV(TT*(1.-DEL),QQ,X,Z,P2,E2)
      CALL STATEV(TT,QQ*(1.+DEL),X,Z,P3,E3)
      CALL STATEV(TT,QQ*(1.-DEL),X,Z,P4,E4)
      PPX=SQRT(SQRT(P0))
      C=0.25*PPX/P0
      DPTX=C*(P1-P2)/(2.*DEL*TT)
      DPQX=C*(P3-P4)/(2.*DEL*QQ)
      EX=E0
      DETX=(E1-E2)/(2.*DEL*TT)
      DEQX=(E3-E4)/(2.*DEL*QQ)
      RETURN
      END
C
C     ------------------------------------------------------------------
C     SUBROUTINE STATEV - ONE EVALUATION OF PRESSURE AND INTERNAL
C     ENERGY PER GRAM AT GIVEN T AND Q (SCALED UNITS - NOTE THAT
C     T IN UNITS OF 1.E7 K IS PRECISELY THE T7 OF THE BFGH
C     FORMULAE, AND THE DENSITY UNIT IS 1 G/CC).
C     ------------------------------------------------------------------
      SUBROUTINE STATEV(TT,QQ,X,Z,P,E)
      COMMON /CONST/ G,SIG,ARAD,RGAS,PI,C256,C4PS,C8PI
      RHO=QQ**3
      Y=1.-X-Z
C     MOLES PER GRAM OF IONS AND OF FREE ELECTRONS
      ANUI=0.9921*X+0.2498*Y+0.04*Z
      ANUE=0.9921*X+0.4997*Y+0.458*Z
C     DEGENERACY PARAMETER G (EQ. A3) AND CORRECTION H (EQ. A7)
      GDEG=3.945E-3*RHO*ANUE/EXP(1.5*ALOG(TT))
      HDEG=1./(1.+3.927E-5*GDEG*GDEG)
     1   +0.176777*GDEG/EXP(0.3333333*ALOG(1.+0.04885*GDEG))
C     RELATIVISTIC FACTOR K(X) (EQS. A9, A12)
      XREL=EXP(0.3333333*ALOG(1.0259E-6*RHO*ANUE))
      RK=0.0864+0.9136*SQRT(1.+0.7567*XREL*XREL)
      PG=RGAS*RHO*TT*(ANUI+ANUE*HDEG/RK)
      PR=ARAD*TT**4/3.
      P=PG+PR
      E=RGAS*TT*(1.5*ANUI+3.*ANUE*HDEG/(1.+RK))+3.*PR/RHO
      RETURN
      END
C
C     ------------------------------------------------------------------
C     SUBROUTINE OPAC - OPACITY AND ITS DERIVATIVES.  THE INTERIOR
C     ABSORPTION IS THE INTERPOLATION FORMULA OF APPENDIX B OF
C     BODENHEIMER, FORBES, GOULD + HENYEY (1965), FITTED TO THE
C     KELLER-MEYEROTT TABLE WITH CONSTANTS MODERNIZED TO COX AND
C     EILERS - HYDROGEN (B1), HELIUM (B2), HEAVY ELEMENTS WITH
C     THE GUILLOTINE BUILT IN (B3), ELECTRON SCATTERING (B4),
C     COMBINED BY THE PUBLISHED MIXING RULE (B5), WITH MESTEL
C     CONDUCTION (B6) JOINED RECIPROCALLY (B7).  BELOW ABOUT
C     1.E4 K AN H-MINUS TERM STANDS IN FOR THE VARDYA ATMOSPHERIC
C     OPACITY TABLE OF THE PRODUCTION CODE, JOINED HARMONICALLY
C     SO THAT KAPPA AND ITS DERIVATIVES REMAIN CONTINUOUS (SEC. V
C     AND FIG. 3 OF THE 1964 PAPER).  DERIVATIVES FOR THE
C     JACOBIAN ARE CENTERED DIFFERENCES OF THE EVALUATOR OPACV.
C     ------------------------------------------------------------------
      SUBROUTINE OPAC(TT,QQ,X,Z,CAP,DCT,DCQ)
      DEL=0.02
      CALL OPACV(TT,QQ,X,Z,C0)
      CALL OPACV(TT*(1.+DEL),QQ,X,Z,C1)
      CALL OPACV(TT*(1.-DEL),QQ,X,Z,C2)
      CALL OPACV(TT,QQ*(1.+DEL),X,Z,C3)
      CALL OPACV(TT,QQ*(1.-DEL),X,Z,C4)
      CAP=C0
      DCT=(C1-C2)/(2.*DEL*TT)
      DCQ=(C3-C4)/(2.*DEL*QQ)
      RETURN
      END
C
C     ------------------------------------------------------------------
C     SUBROUTINE OPACV - ONE EVALUATION OF THE OPACITY (SCALED
C     UNITS - THE SCALED T IS THE T7 OF THE BFGH FORMULAE, THE
C     DENSITY IS IN G/CC, AND THE SCALED OPACITY UNIT IS 1.E-10
C     CM2/G).
C     ------------------------------------------------------------------
      SUBROUTINE OPACV(TT,QQ,X,Z,CAP)
      RHO=QQ**3
      Y=1.-X-Z
      OPX=1.+X
      T2=TT*TT
C     B1 - HYDROGEN
      CK1=6.48E-3*OPX*X*RHO/EXP(4.25*ALOG(TT))
C     B2 - HELIUM
      CK2=186.*RHO*OPX*Y*(1.05E-3/(T2*TT*(10.*TT+1.))
     1   +(2.-Y)/(0.15+TT*(300.*TT-7.))**4)
C     B3 - HEAVY ELEMENTS, GUILLOTINE INCLUDED
      RX=RHO*OPX
      B3A=0.455*SQRT(RX)+1.
      B3B=5.38*T2/RX+1.
      B3C=1.34E5*T2*T2*TT/RX+1.
      B3D=1.44*T2+1./EXP(1.5*ALOG(10.*TT))
      CK3=4.38E3*Z/SQRT(B3A*B3B*B3C*B3D)
C     B4 - ELECTRON SCATTERING
      CK4=0.195*OPX
C     B5 - THE PUBLISHED COMBINATION
      SUM=CK1+CK2+CK3+CK4
      CKR=((CK1+CK2)*(CK3+CK4)+CK3*CK4)/SUM+SUM
C     B6 - CONDUCTION (MESTEL, VIA HASELGROVE + HOYLE)
      ARG=0.004364*OPX*RHO/EXP(1.5*ALOG(TT))
      CKC=301.8/(TT*(1.+EXP(1.6666667*ALOG(ARG))))
C     B7 PLUS THE H-MINUS STAND-IN FOR THE ATMOSPHERIC TABLE
      RKAP=1./CKR+1./CKC
      CHMLG=97.61+ALOG(50.*Z)+0.5*ALOG(RHO)+9.*ALOG(TT)
      IF (CHMLG.LT.-80.) CHMLG=-80.
      RCHM=0.
      IF (CHMLG.LT.85.) RCHM=EXP(-CHMLG)
      CAP=1./(RCHM+1.E-10*RKAP)
      RETURN
      END
C
C     ------------------------------------------------------------------
C     SUBROUTINE ENUC - THERMONUCLEAR ENERGY GENERATION.  THE
C     PROTON-PROTON CHAIN AND THE CNO BI-CYCLE IN THE CLASSICAL
C     INTERPOLATION FORMULAE (SCHWARZSCHILD 1958),
C        EPS(PP) = 2.5E6*RHO*X**2*T6**(-2/3)*EXP(-33.8/T6**(1/3))
C        EPS(CN) = 8.67E27*RHO*X*XCN*T6**(-2/3)
C                      *EXP(-152.3/T6**(1/3)),  XCN = Z/2.
C     RETURNS EPSILON AND ITS DERIVATIVES W.R.T. T AND Q.
C     ------------------------------------------------------------------
      SUBROUTINE ENUC(TT,QQ,X,Z,EPX,DEPTX,DEPQX)
      RHO=QQ**3
      T6=10.*TT
      T6M13=EXP(-0.3333333*ALOG(T6))
      T6M23=T6M13*T6M13
      EPP=0.
      ARG=-33.8*T6M13
      IF (ARG.GT.-80.) EPP=25.*RHO*X*X*T6M23*EXP(ARG)
      ECN=0.
      ARG=-152.3*T6M13
      IF (ARG.GT.-80.) ECN=8.67E22*RHO*X*(0.5*Z)*T6M23*EXP(ARG)
      EPX=EPP+ECN
      DEPTX=(EPP*(-0.6666667+11.267*T6M13)
     1   +ECN*(-0.6666667+50.767*T6M13))/TT
      DEPQX=3.*EPX/QQ
      RETURN
      END
C
C     ------------------------------------------------------------------
C     SUBROUTINE MIX - INSTANTANEOUS MIXING OF THE HYDROGEN
C     ABUNDANCE OVER EACH CONTIGUOUS CONVECTIVE REGION (MASS
C     WEIGHTED MEAN OVER THE POINTS OF THE REGION).
C     ------------------------------------------------------------------
      SUBROUTINE MIX
      COMMON /GRID/ N,XI(201),EMPT(201),EMH(201),EMPH(201)
      COMMON /VARBL/ R(201),F(201),T(201),Q(201),XH(201)
      COMMON /FLAGS/ ICV(201)
      COMMON /STARP/ XM,XMI,ZMET,QHYD
      NM1=N-1
      J=1
   10 IF (ICV(J).EQ.0) GO TO 40
      K1=J
   20 IF (J.EQ.NM1) GO TO 25
      IF (ICV(J+1).EQ.0) GO TO 25
      J=J+1
      GO TO 20
   25 K2=J+1
      SW=0.
      SX=0.
      DO 30 JP=K1,K2
      W=0.
      IF (JP.EQ.1) W=EMH(1)
      IF (JP.GT.1 .AND. JP.LT.N) W=EMH(JP)-EMH(JP-1)
      IF (JP.EQ.N) W=XM-EMH(NM1)
      SW=SW+W
      SX=SX+W*XH(JP)
   30 CONTINUE
      XB=SX/SW
      DO 35 JP=K1,K2
   35 XH(JP)=XB
   40 J=J+1
      IF (J.LE.NM1) GO TO 10
      RETURN
      END
C
C     ------------------------------------------------------------------
C     SUBROUTINE PRINTM - PRINT THE RUN OF THE STRUCTURE
C     VARIABLES THROUGH THE MODEL ON UNIT 6.
C     ------------------------------------------------------------------
      SUBROUTINE PRINTM
      COMMON /GRID/ N,XI(201),EMPT(201),EMH(201),EMPH(201)
      COMMON /VARBL/ R(201),F(201),T(201),Q(201),XH(201)
      COMMON /THERM/ PP(201),DPT(201),DPQ(201),EE(201),DET(201),
     1   DEQ(201),CK(201),DKT(201),DKQ(201),CPA(201),EP(201),
     2   DEPT(201),DEPQ(201)
      COMMON /FLAGS/ ICV(201)
      COMMON /STARP/ XM,XMI,ZMET,QHYD
      WRITE (6,600)
      DO 10 J=1,N
      XL=XI(J)*XI(J)*F(J)
      RHO=Q(J)**3
      PRS=PP(J)**4
      ICP=0
      IF (J.LT.N) ICP=ICV(J)
      WRITE (6,601) J,XI(J),EMPT(J)/XM,1.E10*R(J),1.E35*XL,
     1   1.E7*T(J),RHO,1.E10*PRS,XH(J),1.E-10*CPA(J),1.E5*EP(J),
     2   ICP
   10 CONTINUE
      RETURN
  600 FORMAT (1H0,3H  J,6X,2HXI,7X,3HM/M,9X,1HR,10X,1HL,10X,
     1   1HT,8X,3HRHO,10X,1HP,9X,1HX,6X,5HKAPPA,8X,3HEPS,2X,
     2   2HCV)
  601 FORMAT (1H ,I3,0PF8.4,F9.5,1P8E11.3,I3)
      END
C     ------------------------------------------------------------------
C     BUILD NOTE (NOT PART OF THE 1964 DECK)
C       BIN/IBFTC -O BUILD/HENYEY-7094 HENYEY.F
C       BUILD/HENYEY-7094 < HENYEY.IN
C     MODERN REFERENCE: GFORTRAN -STD=LEGACY -O HENYEY.F
C       ./A.OUT < HENYEY.IN
C     THE SAMPLE INPUT EVOLVES ONE SOLAR MASS FOR ABOUT 6.7E9 YR.
C     ------------------------------------------------------------------
