C     ******************************************************************
C     *                                                                *
C     *    A PROGRAM FOR THE AUTOMATIC COMPUTATION OF STELLAR          *
C     *    EVOLUTION BY THE METHOD OF                                  *
C     *                                                                *
C     *    L. G. HENYEY, J. E. FORBES, AND N. L. GOULD,                *
C     *    ASTROPHYSICAL JOURNAL 139, 306 (1964)  (METHOD II)          *
C     *                                                                *
C     *    THE STAR IS DIVIDED INTO ZONES BY MESH POINTS OF THE        *
C     *    LAGRANGIAN VARIABLE XI, 0 .LE. XI .LE. 1, WITH ALL          *
C     *    QUANTITIES EVALUATED AT THE SAME MESH POINTS.  THE          *
C     *    ARTIFICIAL VARIABLES OF THE PAPER ARE USED THROUGHOUT,      *
C     *         P = (PRESSURE)**(1/4)      (EQ. 8)                     *
C     *         Q = (DENSITY)**(1/3)       (EQ. 9)                     *
C     *         L = XI**2 * F              (EQ. 10, PSEUDOFLUX)        *
C     *         K = 3*KAPPA*P**3/(256*PI*G*SIGMA*T**3)   (EQ. 11)      *
C     *    THE DIFFERENCE EQUATIONS ARE EQS. (22)-(26) OF THE PAPER    *
C     *    WITH BACKWARD TIME DIFFERENCES.  THE LINEARIZED SYSTEM      *
C     *    IS SOLVED BY THE ELIMINATION SCHEME OF EQS. (39)-(46),      *
C     *    WITH THE VECTORS  U = (R,F)  AND  V = (T,Q)  AND THE        *
C     *    RECURSION  DELTA-U(J) + ALPHA(J)*DELTA-V(J) + GAMMA(J) = 0. *
C     *                                                                *
C     *    THE INTERIOR MESH COVERS THE MASS (1-DELS)*M.  THE OUTER    *
C     *    FRACTION DELS = 0.002 IS TREATED BY A SEPARATE ENVELOPE     *
C     *    INTEGRATION (SUBROUTINE ENVEL), WHICH SUPPLIES THE FITTED   *
C     *    BOUNDARY QUANTITIES OF EQS. (30)-(33) AS FUNCTIONS OF THE   *
C     *    TOTAL RADIUS AND LUMINOSITY, IN THE MANNER OF THE VARDYA    *
C     *    OUTER-ZONE PROGRAM REFERRED TO IN THE PAPER.  THE           *
C     *    PHOTOSPHERE IS FIXED BY THE GRAY CONDITIONS                 *
C     *         L = 4*PI*SIGMA*R**2*T**4                               *
C     *         P*KAPPA = (2/3)*G*M/R**2                               *
C     *                                                                *
C     *    THE MATERIAL FUNCTIONS ARE OF THE CLASSICAL KIND - IDEAL    *
C     *    GAS PLUS RADIATION, KRAMERS AND ELECTRON-SCATTERING AND     *
C     *    H-MINUS OPACITY, PROTON-PROTON AND CNO ENERGY GENERATION    *
C     *    (SCHWARZSCHILD 1958).  DEGENERACY IS OMITTED.               *
C     *                                                                *
C     *    INPUT IS READ FROM UNIT 5 (CARD READER).                    *
C     *    OUTPUT IS WRITTEN ON UNIT 6 (LINE PRINTER).                 *
C     *    FORTRAN IV.  SINGLE PRECISION THROUGHOUT.                   *
C     *                                                                *
C     *    CARD 1 (3F10.5)   TOTM   = STELLAR MASS, SOLAR UNITS        *
C     *                      XHYD0  = INITIAL HYDROGEN FRACTION X      *
C     *                      ZMET   = HEAVY ELEMENT FRACTION Z         *
C     *    CARD 2 (2I5,E10.3,F10.5,E10.3,I5)                           *
C     *                      N      = NUMBER OF MESH POINTS (.LE.201)  *
C     *                      NMODS  = NUMBER OF MODELS IN SEQUENCE     *
C     *                      DTYR   = INITIAL TIME STEP, YEARS         *
C     *                      CLIM   = CORRECTION LIMITER (0.1 - 0.3)   *
C     *                      EPSC   = CONVERGENCE TOLERANCE            *
C     *                      NPRIN  = STRUCTURE PRINT INTERVAL         *
C     *                                                                *
C     ******************************************************************
C
C     ------------------------------------------------------------------
C     MAIN PROGRAM - CONTROLS THE EVOLUTIONARY SEQUENCE (FIG. 2 OF
C     THE PAPER).  REACTION-COMPOSITION STEP, HENYEY ITERATIONS,
C     TIME STEP CONTROL.
C     ------------------------------------------------------------------
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      COMMON /GRID/ XI(201),EMPT(201),EMH(201),EMPH(201),N
      COMMON /VARBL/ R(201),F(201),T(201),Q(201),XH(201),X3A(201)
      COMMON /OLDT/ QN(201),EN(201),DTINV
      COMMON /THERM/ PP(201),DPT(201),DPQ(201),EE(201),DET(201),
     1   DEQ(201),CK(201),DKT(201),DKQ(201),CPA(201),EP(201),
     2   DEPT(201),DEPQ(201)
      COMMON /FLAGS/ ICV(201)
      COMMON /CONST/ G,SIG,ARAD,RGAS,PI,C256,C4PS,C8PI
      COMMON /STARP/ XM,XMI,ZMET,QHYD
      COMMON /CTRL/ CLIM,EPSC,ITMAX,ALFA
      COMMON /SURF/ RSTAR,XLSTA,DXR,DXL
      COMMON /BRNC/ DX3MX
      DIMENSION RSV(201),FSV(201),TSV(201),QSV(201),XSV(201),ESV(201)
      DIMENSION X3SV(201)
C
C     PHYSICAL CONSTANTS (C.G.S.)
      G=6.668D-8
      SIG=5.67D-5
      ARAD=7.565D-15
      RGAS=8.25D7
      PI=3.1415927
      C256=256.*PI*G*SIG
      C4PS=4.*PI*SIG
      C8PI=8./PI
      SECYR=3.156D7
C     ENERGY RELEASE PER GRAM OF HYDROGEN CONSUMED
      QHYD=6.3D18
C
C     READ THE CONTROL CARDS (UNIT 5 = CARD READER)
      READ (5,500) TOTM,XHYD0,ZMET,X3IN
      READ (5,501) N,NMODS,DTYR,CLIM,EPSC,NPRIN,ALFA
      IF (ALFA.LE.0.) ALFA=1.5
      XM=TOTM*1.989D33
C     THE INTERIOR MESH COVERS THE MASS XMI = (1-DELS)*M.  THE
C     OUTER FRACTION DELS IS CARRIED BY THE SEPARATE ENVELOPE
C     INTEGRATION (SUBROUTINE ENVEL), IN THE MANNER OF THE
C     OUTER-ZONE PROGRAM OF THE PAPER (EQS. 30-33)
      DELS=2.0D-3
      XMI=XM*(1.-DELS)
      WRITE (6,510)
      WRITE (6,511)
      WRITE (6,512)
      WRITE (6,513) XM,XHYD0,ZMET
      WRITE (6,514) N,NMODS,DTYR
      WRITE (6,516) X3IN
      WRITE (6,517) ALFA
C
C     SET UP THE FIXED MASS MESH.  THE MASS DISTRIBUTION M(XI) IS
C     NEVER VARIED (SEC. V OF THE PAPER).  WE ADOPT
C         M(XI) = M * XI**3 * (10 - 15*XI + 6*XI**2)
C     WHICH CONCENTRATES THE ZONING AT BOTH CENTER AND SURFACE.
      NM1=N-1
      DO 10 J=1,N
      XX=DBLE(J-1)/DBLE(NM1)
      XI(J)=XX
      EMPT(J)=XMI*XX**3*(10.-15.*XX+6.*XX*XX)
   10 CONTINUE
      DO 20 J=1,NM1
      XX=0.5*(XI(J)+XI(J+1))
      EMH(J)=XMI*XX**3*(10.-15.*XX+6.*XX*XX)
      EMPH(J)=30.*XMI*XX*XX*(1.-XX)**2
   20 CONTINUE
C
C     UNIFORM INITIAL COMPOSITION.  X3IN .GE. 0 GIVES A UNIFORM
C     INITIAL HE3 MASS FRACTION (LBA97 TAKE ZERO).  X3IN .LT. 0
C     SETS HE3 TO ITS LOCAL EQUILIBRIUM VALUE IN THE FIRST
C     APPROXIMATION, FOR COMPARISON WITH THE EQUILIBRIUM-CHAIN
C     PROGRAM IN THE REPOSITORY ROOT.
      X3G=MAX(X3IN,0.D0)
      DO 30 J=1,N
      XH(J)=XHYD0
      X3A(J)=X3G
      QN(J)=0.
      EN(J)=0.
   30 CONTINUE
C
C     FIRST APPROXIMATION FROM THE EMDEN POLYTROPE N=3
      CALL START(TOTM,XHYD0,X3G)
      IF (X3IN.GE.0.) GO TO 35
      DO 32 J=1,N
      CALL RATES(T(J),Q(J),XHYD0,0.D0,ZMET,RPZ,C3Z,C4Z,R14Z,
     1   D1,D2,D3,D4,D5,D6,D7,D8)
      X3E=0.
      IF (C3Z.GT.1.D-30) X3E=(-C4Z+SQRT(C4Z*C4Z+8.*C3Z*RPZ))
     1   /(4.*C3Z)
      X3A(J)=MIN(X3E,1.D-2)
   32 CONTINUE
   35 CONTINUE
C
C     ------------------------------------------------------------------
C     INITIAL (STATIC) MODEL.  THE TIME DERIVATIVE TERMS ARE
C     SUPPRESSED BY SETTING 1/(DELTA T) = 0.
C     ------------------------------------------------------------------
      DTINV=0.
      ITMAX=60
      MODNO=1
      WRITE (6,515) MODNO
      CALL SOLVE(NIT,IER)
      IF (IER.EQ.0) GO TO 40
      WRITE (6,540)
      STOP 1
   40 CONTINUE
      ITMAX=30
      AGEYR=0.
      DT=DTYR*SECYR
      DTY2=DTYR
      WRITE (6,520)
      XLSOL=XLSTA/3.86D33
      RSOL=RSTAR/6.96D10
      TEFF=SQRT(SQRT(XLSTA/(C4PS*RSTAR*RSTAR)))
      RHOC=Q(1)**3
      PC=PP(1)**4
      WRITE (6,521) MODNO,AGEYR,DTY2,NIT,XLSOL,RSOL,TEFF,T(1),RHOC,
     1   PC,XH(1)
      CALL PRINTM
C
C     ------------------------------------------------------------------
C     EVOLUTIONARY SEQUENCE
C     ------------------------------------------------------------------
      IF (NMODS.LE.1) STOP
      DO 300 NMOD=2,NMODS
C     SAVE THE CONVERGED MODEL FOR THE OLD EPOCH AND FOR RETRIES
      DO 210 J=1,N
      QN(J)=Q(J)
      EN(J)=EE(J)
      RSV(J)=R(J)
      FSV(J)=F(J)
      TSV(J)=T(J)
      QSV(J)=Q(J)
      XSV(J)=XH(J)
      X3SV(J)=X3A(J)
      ESV(J)=EP(J)
  210 CONTINUE
      RSSV=RSTAR
      XLSV=XLSTA
      NTRY=0
C     COMPOSITION STEP - THE NUCLEAR NETWORK ADVANCES X(H1) AND
C     X(HE3) BY THE CONVERGED RATES (HE3 BY AN UNCONDITIONALLY
C     STABLE BACKWARD-EULER STEP), AND CONVECTIVE REGIONS ARE
C     THEN MIXED (FIRST BOX OF FIG. 2).  ON A RETRY THE
C     COMPOSITION IS FIRST RESTORED.
  220 DO 230 J=1,N
      XH(J)=XSV(J)
      X3A(J)=X3SV(J)
  230 CONTINUE
      CALL BURN(DT)
      CALL MIX
      DTINV=1./DT
      CALL SOLVE(NIT,IER)
      IF (IER.EQ.0) GO TO 260
C     NO CONVERGENCE - RESTORE THE MODEL, HALVE THE TIME STEP, RETRY
      NTRY=NTRY+1
      IF (NTRY.LE.8) GO TO 240
      WRITE (6,540)
      STOP 2
  240 DO 250 J=1,N
      R(J)=RSV(J)
      F(J)=FSV(J)
      T(J)=TSV(J)
      Q(J)=QSV(J)
  250 CONTINUE
      RSTAR=RSSV
      XLSTA=XLSV
      DT=0.5*DT
      WRITE (6,541) DT
      GO TO 220
C     CONVERGED - PRINT THE TRACK LINE
  260 AGEYR=AGEYR+DT/SECYR
      DTY2=DT/SECYR
      XLSOL=XLSTA/3.86D33
      RSOL=RSTAR/6.96D10
      TEFF=SQRT(SQRT(XLSTA/(C4PS*RSTAR*RSTAR)))
      RHOC=Q(1)**3
      PC=PP(1)**4
      WRITE (6,521) NMOD,AGEYR,DTY2,NIT,XLSOL,RSOL,TEFF,T(1),RHOC,
     1   PC,XH(1)
      IF (MOD(NMOD,NPRIN).EQ.0) CALL PRINTM
C     TIME STEP CONTROL - GROW WHEN CONVERGENCE IS EASY, SHRINK
C     WHEN IT IS HARD, AND LIMIT THE CENTRAL HYDROGEN DEPLETION
C     TO ABOUT 3 PERCENT PER STEP
      IF (NIT.LE.5) DT=1.4*DT
      IF (NIT.GE.12) DT=0.7*DT
C     HOLD THE HE3 CHANGE PER STEP TO ABOUT TEN PER CENT
      IF (DX3MX.GT.0.10) DT=0.6*DT
      DTX=0.03*MAX(XH(1),0.02)*QHYD/MAX(EP(1),1.D-20)
      DT=MIN(DT,DTX,3.D16)
  300 CONTINUE
      CALL PRINTM
      STOP
C
  500 FORMAT (4F10.5)
  501 FORMAT (2I5,E10.3,F10.5,E10.3,I5,F10.5)
  510 FORMAT ('1',20X,'HENYEY STELLAR EVOLUTION PROGRAM ')
  511 FORMAT (21X,'METHOD OF HENYEY, FORBES + GOULD')
  512 FORMAT (21X,'AP. J. 139, 306 (1964)')
  513 FORMAT ('0',' MASS = ',1PE11.4,'  X(H) = ',0PF7.4,'  Z =  ',
     1   F7.4)
  514 FORMAT (' N     =',I5,'  MODELS=',I5,'  DTYR=',1PE10.3)
  515 FORMAT ('0','STATIC INITIAL MODEL ',I4)
  516 FORMAT (' HE3(0)=',F9.5,'   (NEGATIVE = LOCAL EQUILIBRIUM)')
  517 FORMAT (' ALPHA =',F8.3,'   (MIXING LENGTH/SCALE HEIGHT)')
  520 FORMAT ('0','MODEL',5X,'AGE(YR)',6X,'DT(YR)',3X,'IT',3X,
     1   'L/LSUN',5X,'R/RSUN',7X,'TEFF',9X,'TC',7X,'RHOC',9X,
     2   'PC',9X,'XC')
  521 FORMAT (' ',I4,1P2E12.4,I4,1P7E11.3)
  540 FORMAT ('0NO CONVERGENCE ')
  541 FORMAT ('0TIME STEP HALVED, DT(S) =',1PE11.3)
      END
C
C     ------------------------------------------------------------------
C     SUBROUTINE START - FIRST APPROXIMATION TO THE CONFIGURATION.
C     THE PAPER (SEC. V) SCALES A PREVIOUS MODEL HOMOLOGOUSLY.
C     HAVING NO PREVIOUS MODEL, THE GENERATING PROGRAM TAKES THE
C     TOTAL RADIUS AND LUMINOSITY FROM CRUDE MASS-RADIUS AND
C     MASS-LUMINOSITY RELATIONS, OBTAINS THE FITTING VALUES FROM
C     THE ENVELOPE INTEGRATION, AND MARCHES A ROUGH MODEL INWARD
C     ZONE BY ZONE WITH THE HYDROSTATIC RELATION AND THE SMALLER
C     OF THE RADIATIVE AND ADIABATIC GRADIENTS.  THE RADIUS RUN
C     IS TAKEN FROM THE MASS-RADIUS SHAPE OF THE EMDEN POLYTROPE
C     N=3 (STANDARD TABULATED VALUES).  THE RESULT NEED ONLY BE
C     GOOD ENOUGH TO START THE NEWTON-RAPHSON PROCESS.
C     ------------------------------------------------------------------
      SUBROUTINE START(TOTM,XHYD0,X3G)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      COMMON /GRID/ XI(201),EMPT(201),EMH(201),EMPH(201),N
      COMMON /VARBL/ R(201),F(201),T(201),Q(201),XH(201),X3A(201)
      COMMON /CONST/ G,SIG,ARAD,RGAS,PI,C256,C4PS,C8PI
      COMMON /STARP/ XM,XMI,ZMET,QHYD
      COMMON /SURF/ RSTAR,XLSTA,DXR,DXL
      DIMENSION XLE(29),PHE(29)
C     EMDEN COORDINATE AND MASS FUNCTION PHI = -XI**2*DTHETA/DXI
C     FOR THE POLYTROPE N=3, AT INTERVALS OF 0.25
      DATA XLE/0.,.25,.50,.75,1.00,1.25,1.50,1.75,2.00,2.25,2.50,
     1   2.75,3.00,3.25,3.50,3.75,4.00,4.25,4.50,4.75,5.00,5.25,
     2   5.50,5.75,6.00,6.25,6.50,6.75,6.89685/
      DATA PHE/0.,.005112,.038710,.119605,.252129,.427603,.629801,
     1   .840957,1.045963,1.234240,1.399805,1.540418,1.656448,
     2   1.749846,1.823360,1.879998,1.922704,1.954176,1.976783,
     3   1.992547,2.003150,2.009969,2.014105,2.016422,2.017579,
     4   2.018063,2.018212,2.018235,2.018235/
      Y=1.-XHYD0-ZMET
      RMU=1.984*XHYD0+0.7495*Y+0.5*ZMET
C     MASS-RADIUS AND MASS-LUMINOSITY GUESSES (SOLAR UNITS)
      RG=6.96D10*TOTM**0.9
      XL=3.86D33*TOTM**3.5
      RSTAR=RG
      XLSTA=XL
C     FITTING VALUES FROM THE ENVELOPE INTEGRATION
      CALL ENVEL(RG,XL,XHYD0,RF,TF,QF)
C     RADIUS AT EACH MESH POINT FROM THE POLYTROPIC MASS-RADIUS
C     SHAPE, RESCALED TO JOIN THE ENVELOPE AT THE FITTING POINT.
C     IN THE FIRST TABLE INTERVAL THE SERIES PHI = XI**3/3 IS
C     USED IN PLACE OF LINEAR INTERPOLATION.
      DO 20 J=1,N
      XF=EMPT(J)/XM
      TARG=XF*2.018235
      DO 12 I=1,28
      II=I
      IF (PHE(I+1).GE.TARG) GO TO 14
   12 CONTINUE
      II=28
   14 IF (II.GT.1) GO TO 16
      XIE=(3.*TARG)**0.3333333
      GO TO 18
   16 DEN=PHE(II+1)-PHE(II)
      FR=0.5
      IF (DEN.GT.1.D-5) FR=(TARG-PHE(II))/DEN
      XIE=XLE(II)+FR*(XLE(II+1)-XLE(II))
   18 R(J)=XIE
   20 CONTINUE
      RN0=R(N)
      DO 22 J=1,N
   22 R(J)=R(J)*(RF/RN0)
      R(1)=0.
      T(N)=TF
      Q(N)=QF
      F(N)=XL
C     MARCH THE PRESSURE AND TEMPERATURE INWARD ZONE BY ZONE
      C64=3./(64.*PI*SIG*G)
      PJ1=RGAS*QF**3*TF*RMU+ARAD*TF**4/3.
      NM1=N-1
      DO 60 JJ=1,NM1
      J=N-JJ
      DELM=EMPT(J+1)-EMPT(J)
      EMM=EMH(J)
      RJ1=R(J+1)
      TJ1=T(J+1)
C     HYDROSTATIC PRESSURE STEP (THE FACTORS ARE STAGED TO AVOID
C     OVERFLOW OF R**4 IN SINGLE PRECISION)
      GS=G*EMM/(RJ1*RJ1)
      P=PJ1+GS*(DELM/(12.566371*RJ1*RJ1))
C     TEMPERATURE STEP WITH THE SMALLER OF THE RADIATIVE AND
C     ADIABATIC GRADIENTS
      CALL OPAC(TJ1,Q(J+1),XHYD0,ZMET,CPS,D1,D2)
      XF=EMM/XM
      XLZ=XL*XF*(2.-XF)
      GRR=C64*CPS*(XLZ/EMM)*(PJ1/TJ1**4)
      GRAD=MIN(GRR,0.40)
      T(J)=TJ1*(P/PJ1)**GRAD
C     DENSITY FROM THE GAS PRESSURE
      PG=P-ARAD*T(J)**4/3.
      IF (PG.LT.0.1*P) PG=0.1*P
      RHO=PG/(RGAS*T(J)*RMU)
      Q(J)=RHO**0.3333333
      PJ1=P
   60 CONTINUE
C     PSEUDOFLUX GUESS FROM THE INTEGRATED NUCLEAR ENERGY RELEASE
C     OF THE MARCHED STRUCTURE, SO THAT THE ENERGY EQUATION IS
C     ROUGHLY SATISFIED FROM THE OUTSET.  THE MISMATCH WITH THE
C     LUMINOSITY GUESS AT THE FITTING POINT IS REMOVED BY THE
C     NEWTON-RAPHSON PROCESS.
      XLN=0.
      F(1)=0.
      DO 70 J=2,N
      CALL ENUC(T(J-1),Q(J-1),XHYD0,X3G,ZMET,E1,D1,D2)
      CALL ENUC(T(J),Q(J),XHYD0,X3G,ZMET,E2,D1,D2)
      XLN=XLN+0.5*(E1+E2)*(EMPT(J)-EMPT(J-1))
      F(J)=XLN/(XI(J)*XI(J))
   70 CONTINUE
      RETURN
      END
C
C     ------------------------------------------------------------------
C     SUBROUTINE SOLVE - ONE CONVERGED MODEL BY THE NEWTON-RAPHSON
C     (HENYEY) PROCESS.  THE LINEARIZED DIFFERENCE EQUATIONS ARE
C     REDUCED ZONE BY ZONE WITH THE RECURSION OF EQ. (44),
C          DELTA-U(J) + ALPHA(J)*DELTA-V(J) + GAMMA(J) = 0,
C     STARTING FROM ALPHA(1) = GAMMA(1) = 0 (CENTRAL CONDITION,
C     EQ. 41).  THE STORED ROWS OF EQ. (46) GIVE THE BACKWARD
C     SUBSTITUTION.  ALL CORRECTIONS ARE CARRIED IN RELATIVE FORM
C     (COLUMNS OF THE JACOBIAN SCALED BY THE CURRENT VALUES) TO
C     CONTROL THE ILL-CONDITIONING NOTED IN THE PAPER.
C     IER = 0 CONVERGED, 1 TOO MANY ITERATIONS, 2 SINGULAR MATRIX.
C     ------------------------------------------------------------------
      SUBROUTINE SOLVE(NIT,IER)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      COMMON /GRID/ XI(201),EMPT(201),EMH(201),EMPH(201),N
      COMMON /VARBL/ R(201),F(201),T(201),Q(201),XH(201),X3A(201)
      COMMON /OLDT/ QN(201),EN(201),DTINV
      COMMON /THERM/ PP(201),DPT(201),DPQ(201),EE(201),DET(201),
     1   DEQ(201),CK(201),DKT(201),DKQ(201),CPA(201),EP(201),
     2   DEPT(201),DEPQ(201)
      COMMON /HENMT/ AL(2,2,201),GA(2,201),ZE(2,2,201),ET(2,2,201),
     1   BE(2,2,201),TQ(2,201),SU(2,201),SV(2,201),DU(2,201),
     2   DV(2,201)
      COMMON /FLAGS/ ICV(201)
      COMMON /CONST/ G,SIG,ARAD,RGAS,PI,C256,C4PS,C8PI
      COMMON /STARP/ XM,XMI,ZMET,QHYD
      COMMON /CTRL/ CLIM,EPSC,ITMAX,ALFA
      COMMON /SURF/ RSTAR,XLSTA,DXR,DXL
      DIMENSION AA(4,9)
      IER=0
      NM1=N-1
      DMAXP=1.
      DO 200 ITER=1,ITMAX
      CALL PHYSIC
C     LOCATE THE CONVECTIVE ZONES BY THE STABILITY CRITERION
C     (EQ. 27).  THE PLACING OF THESE BOUNDARIES IS THE MOST
C     TROUBLESOME PART OF THE METHOD (SEC. IV OF THE PAPER).  IN
C     PLACE OF THE INTERPOLATION AMONG COMPLETE MODELS (FIG. 1)
C     A SIMPLER DEVICE IS USED HERE - AFTER THE EARLY ITERATIONS
C     A ZONE IS RECLASSIFIED ONLY WHEN THE CRITERION IS EXCEEDED
C     BY A DEFINITE MARGIN, AND THE PATTERN IS FROZEN ENTIRELY
C     ONCE THE ITERATION IS WELL ADVANCED, TO PREVENT AN
C     OSCILLATORY INSTABILITY OF THE BOUNDARY.
      IF (ITER.LE.3) CALL CONVCK(0)
      IF (ITER.GT.3 .AND. ITER.LE.12) CALL CONVCK(1)
C     SCALES FOR THE RELATIVE CORRECTIONS
      FLR=1.D-6*ABS(F(N))
      IF (FLR.LE.0.) FLR=1.
      DO 25 J=1,N
      SU(1,J)=R(J)
      IF (SU(1,J).LE.0.) SU(1,J)=1.
      SU(2,J)=ABS(F(J))
      IF (SU(2,J).LT.FLR) SU(2,J)=FLR
      SV(1,J)=T(J)
      SV(2,J)=Q(J)
   25 CONTINUE
C     CENTRAL BOUNDARY CONDITION, EQ. (41) - DELTA-U(1) = 0
      DO 28 K=1,2
      GA(K,1)=0.
      DO 28 L=1,2
   28 AL(L,K,1)=0.
C
C     FORWARD ELIMINATION OVER THE ZONES
      DO 100 J=1,NM1
      CALL ZONEQ(J,AA)
C     SCALE THE COLUMNS BY THE CURRENT VALUES OF THE VARIABLES
      DO 32 I=1,4
      AA(I,1)=AA(I,1)*SU(1,J)
      AA(I,2)=AA(I,2)*SU(2,J)
      AA(I,3)=AA(I,3)*SV(1,J)
      AA(I,4)=AA(I,4)*SV(2,J)
      AA(I,5)=AA(I,5)*SU(1,J+1)
      AA(I,6)=AA(I,6)*SU(2,J+1)
      AA(I,7)=AA(I,7)*SV(1,J+1)
      AA(I,8)=AA(I,8)*SV(2,J+1)
   32 CONTINUE
C     ELIMINATE DELTA-U(J) BY THE RECURSION, EQ. (44)
      DO 34 I=1,4
      AA(I,9)=AA(I,9)-AA(I,1)*GA(1,J)-AA(I,2)*GA(2,J)
   34 CONTINUE
      DO 36 I=1,4
      DO 36 K=1,2
   36 AA(I,2+K)=AA(I,2+K)-AA(I,1)*AL(1,K,J)-AA(I,2)*AL(2,K,J)
C     NORMALIZE EACH ROW BY ITS LARGEST COEFFICIENT
      DO 44 I=1,4
      BIG=0.
      DO 40 K=3,8
      IF (ABS(AA(I,K)).GT.BIG) BIG=ABS(AA(I,K))
   40 CONTINUE
      IF (BIG.GT.0.) GO TO 42
      IER=2
      WRITE (6,542) J
      RETURN
   42 BIG=1./BIG
      DO 43 K=3,9
   43 AA(I,K)=AA(I,K)*BIG
   44 CONTINUE
C     GAUSSIAN ELIMINATION OF DELTA-V(J) (COLUMNS 3 AND 4) WITH
C     ROW INTERCHANGES
      DO 60 KC=1,2
      IC=KC+2
      IP=KC
      BIG=ABS(AA(KC,IC))
      KP1=KC+1
      DO 46 I=KP1,4
      IF (ABS(AA(I,IC)).LE.BIG) GO TO 46
      BIG=ABS(AA(I,IC))
      IP=I
   46 CONTINUE
      IF (IP.EQ.KC) GO TO 50
      DO 48 K=3,9
      TMP=AA(KC,K)
      AA(KC,K)=AA(IP,K)
      AA(IP,K)=TMP
   48 CONTINUE
   50 IF (ABS(AA(KC,IC)).GT.1.D-12) GO TO 52
      IER=2
      WRITE (6,542) J
      RETURN
   52 DO 56 I=KP1,4
      FAC=AA(I,IC)/AA(KC,IC)
      DO 54 K=IC,9
   54 AA(I,K)=AA(I,K)-FAC*AA(KC,K)
   56 CONTINUE
   60 CONTINUE
C     STORE ROWS 1-2 FOR THE BACKWARD SUBSTITUTION (EQ. 46)
      DO 64 L=1,2
      TQ(L,J)=AA(L,9)
      DO 64 K=1,2
      ZE(L,K,J)=AA(L,2+K)
      ET(L,K,J)=AA(L,4+K)
      BE(L,K,J)=AA(L,6+K)
   64 CONTINUE
C     ROWS 3-4 GIVE ALPHA AND GAMMA AT J+1 (EQ. 45)
      C11=AA(3,5)
      C12=AA(3,6)
      C21=AA(4,5)
      C22=AA(4,6)
      DET2=C11*C22-C12*C21
      IF (ABS(DET2).GT.1.D-20) GO TO 66
      IER=2
      WRITE (6,542) J
      RETURN
   66 AL(1,1,J+1)=(C22*AA(3,7)-C12*AA(4,7))/DET2
      AL(1,2,J+1)=(C22*AA(3,8)-C12*AA(4,8))/DET2
      AL(2,1,J+1)=(C11*AA(4,7)-C21*AA(3,7))/DET2
      AL(2,2,J+1)=(C11*AA(4,8)-C21*AA(3,8))/DET2
      GA(1,J+1)=(C22*AA(3,9)-C12*AA(4,9))/DET2
      GA(2,J+1)=(C11*AA(4,9)-C21*AA(3,9))/DET2
  100 CONTINUE
C
C     OUTER BOUNDARY - THE FITTING CONDITIONS, EQS. (37)-(38) AND
C     (42)-(43).  THE OUTER ENVELOPE (MASS FRACTION DELS) IS
C     INTEGRATED SEPARATELY AS A FUNCTION OF THE TOTAL RADIUS AND
C     LUMINOSITY, GIVING THE FITTED QUANTITIES OF EQS. (30)-(33).
C     THE PAPER INTERPOLATES AMONG FOUR STORED ATMOSPHERE CASES
C     (FIG. 4) - HERE THE INTEGRATION IS SIMPLY REPEATED AND THE
C     PARTIAL DERIVATIVES ARE OBTAINED BY DIFFERENCING.
      CALL ENVEL(RSTAR,XLSTA,XH(N),RF0,TF0,QF0)
      DH=0.02
      CALL ENVEL(RSTAR*(1.+DH),XLSTA,XH(N),RF1,TF1,QF1)
      CALL ENVEL(RSTAR,XLSTA*(1.+DH),XH(N),RF2,TF2,QF2)
      FJ11=(RF1-RF0)/DH
      FJ12=(RF2-RF0)/DH
      FJ31=(TF1-TF0)/DH
      FJ32=(TF2-TF0)/DH
      FJ41=(QF1-QF0)/DH
      FJ42=(QF2-QF0)/DH
      SR1=R(N)-RF0
      SR2=F(N)-XLSTA
      SR3=T(N)-TF0
      SR4=Q(N)-QF0
      S1=SU(1,N)
      S2=SU(2,N)
      S3=SV(1,N)
      S4=SV(2,N)
C     SUBSTITUTE THE LINEARIZED FITTING RELATIONS INTO THE
C     RECURSION (44) AT J = N AND SOLVE FOR THE RELATIVE CHANGES
C     OF THE TOTAL RADIUS AND LUMINOSITY
      A11=FJ11/S1+AL(1,1,N)*FJ31/S3+AL(1,2,N)*FJ41/S4
      A12=FJ12/S1+AL(1,1,N)*FJ32/S3+AL(1,2,N)*FJ42/S4
      B1=SR1/S1+AL(1,1,N)*SR3/S3+AL(1,2,N)*SR4/S4-GA(1,N)
      A21=AL(2,1,N)*FJ31/S3+AL(2,2,N)*FJ41/S4
      A22=XLSTA/S2+AL(2,1,N)*FJ32/S3+AL(2,2,N)*FJ42/S4
      B2=SR2/S2+AL(2,1,N)*SR3/S3+AL(2,2,N)*SR4/S4-GA(2,N)
      DET2=A11*A22-A12*A21
      IF (ABS(DET2).GT.1.D-20) GO TO 120
      IER=2
      WRITE (6,542) N
      RETURN
  120 DXR=(B1*A22-B2*A12)/DET2
      DXL=(B2*A11-B1*A21)/DET2
      DV(1,N)=(FJ31*DXR+FJ32*DXL-SR3)/S3
      DV(2,N)=(FJ41*DXR+FJ42*DXL-SR4)/S4
      DU(1,N)=(FJ11*DXR+FJ12*DXL-SR1)/S1
      DU(2,N)=(XLSTA*DXL-SR2)/S2
C
C     BACKWARD SUBSTITUTION, EQS. (46) AND (44), FOR DECREASING J
      DO 140 JJ=1,NM1
      J=N-JJ
      T1=TQ(1,J)+ET(1,1,J)*DU(1,J+1)+ET(1,2,J)*DU(2,J+1)
     1   +BE(1,1,J)*DV(1,J+1)+BE(1,2,J)*DV(2,J+1)
      T2=TQ(2,J)+ET(2,1,J)*DU(1,J+1)+ET(2,2,J)*DU(2,J+1)
     1   +BE(2,1,J)*DV(1,J+1)+BE(2,2,J)*DV(2,J+1)
      IF (ABS(ZE(2,2,J)).GT.1.D-20 .AND. ABS(ZE(1,1,J)).GT.1.D-20)
     1   GO TO 130
      IER=2
      WRITE (6,542) J
      RETURN
  130 DV(2,J)=-T2/ZE(2,2,J)
      DV(1,J)=-(T1+ZE(1,2,J)*DV(2,J))/ZE(1,1,J)
      DU(1,J)=-AL(1,1,J)*DV(1,J)-AL(1,2,J)*DV(2,J)-GA(1,J)
      DU(2,J)=-AL(2,1,J)*DV(1,J)-AL(2,2,J)*DV(2,J)-GA(2,J)
  140 CONTINUE
C
C     LARGEST RELATIVE CORRECTION.  FOLLOWING THE PAPER (SEC. V),
C     DELTA-F/F IS EXAMINED ONLY AT THE SURFACE, SINCE F MAY PASS
C     THROUGH ZERO AT INTERIOR POINTS.
      DMAX=0.
      DO 150 J=1,N
      IF (J.GT.1 .AND. ABS(DU(1,J)).GT.DMAX) DMAX=ABS(DU(1,J))
      IF (ABS(DV(1,J)).GT.DMAX) DMAX=ABS(DV(1,J))
      IF (ABS(DV(2,J)).GT.DMAX) DMAX=ABS(DV(2,J))
  150 CONTINUE
      IF (ABS(DU(2,N)).GT.DMAX) DMAX=ABS(DU(2,N))
      IF (ABS(DXR).GT.DMAX) DMAX=ABS(DXR)
      IF (ABS(DXL).GT.DMAX) DMAX=ABS(DXL)
C     LIMIT THE INCREMENTS (SEC. V OF THE PAPER)
      DAMP=1.
      IF (DMAX.GT.CLIM) DAMP=CLIM/DMAX
      DO 160 J=1,N
      R(J)=R(J)+DAMP*SU(1,J)*DU(1,J)
      F(J)=F(J)+DAMP*SU(2,J)*DU(2,J)
      T(J)=T(J)+DAMP*SV(1,J)*DV(1,J)
      Q(J)=Q(J)+DAMP*SV(2,J)*DV(2,J)
  160 CONTINUE
      RSTAR=RSTAR*(1.+DAMP*DXR)
      XLSTA=XLSTA*(1.+DAMP*DXL)
      WRITE (6,530) ITER,DMAX,DAMP
      DMAXP=DMAX
      IF (DMAX.LT.EPSC) GO TO 210
      IF (ITER.GE.20 .AND. DMAX.LT.20.*EPSC) GO TO 210
  200 CONTINUE
      IER=1
      NIT=ITMAX
      RETURN
  210 NIT=ITER
      CALL PHYSIC
      RETURN
  530 FORMAT (' ITER=',I3,'  MAX CORRECT=',1PE10.2,'  DAMP=',
     1   0PF6.3)
  542 FORMAT ('0SINGULAR MATRIX AT ZONE ',I4)
      END
C
C     ------------------------------------------------------------------
C     SUBROUTINE PHYSIC - THE MATERIAL FUNCTIONS P, E, K, EPSILON
C     AND THEIR PARTIAL DERIVATIVES WITH RESPECT TO T AND Q AT
C     EVERY MESH POINT (SECOND BOX OF FIG. 2).
C     ------------------------------------------------------------------
      SUBROUTINE PHYSIC
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      COMMON /GRID/ XI(201),EMPT(201),EMH(201),EMPH(201),N
      COMMON /VARBL/ R(201),F(201),T(201),Q(201),XH(201),X3A(201)
      COMMON /THERM/ PP(201),DPT(201),DPQ(201),EE(201),DET(201),
     1   DEQ(201),CK(201),DKT(201),DKQ(201),CPA(201),EP(201),
     2   DEPT(201),DEPQ(201)
      COMMON /CONST/ G,SIG,ARAD,RGAS,PI,C256,C4PS,C8PI
      COMMON /STARP/ XM,XMI,ZMET,QHYD
      DO 10 J=1,N
C     RECIPROCAL MEAN MOLECULAR WEIGHT OF THE FULLY IONIZED
C     MIXTURE (H1, HE3, HE4, METALS)
      X4J=MAX(1.-XH(J)-X3A(J)-ZMET,0.D0)
      RMI=1.984*XH(J)+0.9947*X3A(J)+0.7495*X4J+0.5*ZMET
      CALL STATE(T(J),Q(J),RMI,PP(J),DPT(J),DPQ(J),EE(J),
     1   DET(J),DEQ(J))
      CALL OPAC(T(J),Q(J),XH(J),ZMET,CPA(J),DCT,DCQ)
C     THE MODIFIED OPACITY VARIABLE K OF EQ. (11)
      CK(J)=3.*CPA(J)*PP(J)**3/(C256*T(J)**3)
      DKT(J)=CK(J)*(DCT/CPA(J)+3.*DPT(J)/PP(J)-3./T(J))
      DKQ(J)=CK(J)*(DCQ/CPA(J)+3.*DPQ(J)/PP(J))
      CALL ENUC(T(J),Q(J),XH(J),X3A(J),ZMET,EP(J),DEPT(J),DEPQ(J))
   10 CONTINUE
      RETURN
      END
C
C     ------------------------------------------------------------------
C     SUBROUTINE CONVCK - STABILITY AGAINST CONVECTION FOR EACH
C     ZONE (EQ. 27).  THE ZONE IS CONVECTIVE WHEN THE RADIATIVE
C     GRADIENT DLOG(T)/DLOG(P) EXCEEDS THE ADIABATIC VALUE 0.40.
C     WHERE CONVECTIVE, THE ADIABATIC CONDITION (EQ. 26) REPLACES
C     THE RADIATIVE CONDITION (EQ. 25) IN THE DIFFERENCE SYSTEM.
C     FOR MODE = 1 A ZONE IS RECLASSIFIED ONLY WHEN THE CRITERION
C     IS PASSED BY A TEN PER CENT MARGIN (HYSTERESIS), WHICH
C     SUPPRESSES THE FLUTTER OF THE CONVECTIVE BOUNDARIES DURING
C     THE ITERATION.
C     ------------------------------------------------------------------
      SUBROUTINE CONVCK(MODE)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      COMMON /GRID/ XI(201),EMPT(201),EMH(201),EMPH(201),N
      COMMON /VARBL/ R(201),F(201),T(201),Q(201),XH(201),X3A(201)
      COMMON /THERM/ PP(201),DPT(201),DPQ(201),EE(201),DET(201),
     1   DEQ(201),CK(201),DKT(201),DKQ(201),CPA(201),EP(201),
     2   DEPT(201),DEPQ(201)
      COMMON /FLAGS/ ICV(201)
      COMMON /CONST/ G,SIG,ARAD,RGAS,PI,C256,C4PS,C8PI
      COMMON /STARP/ XM,XMI,ZMET,QHYD
      NM1=N-1
      C64=3./(64.*PI*SIG*G)
      DO 10 J=1,NM1
      TB=0.5*(T(J)+T(J+1))
      PB=(0.5*(PP(J)+PP(J+1)))**4
      CB=0.5*(CPA(J)+CPA(J+1))
      XB=0.5*(XI(J)+XI(J+1))
      FB=0.5*(F(J)+F(J+1))
      XLB=XB*XB*FB
      GR=C64*CB*(XLB/EMH(J))*(PB/TB**4)
      IF (MODE.EQ.1) GO TO 5
      ICV(J)=0
      IF (GR.GT.0.40) ICV(J)=1
      GO TO 10
    5 IF (GR.GT.0.44) ICV(J)=1
      IF (GR.LT.0.36) ICV(J)=0
   10 CONTINUE
      RETURN
      END
C
C     ------------------------------------------------------------------
C     SUBROUTINE ZONEQ - THE FOUR DIFFERENCE EQUATIONS OF THE ZONE
C     BETWEEN POINTS J AND J+1, EQS. (22), (23), (24), AND (25) OR
C     (26), WITH THEIR PARTIAL DERIVATIVES (THE TENSORS OF EQS.
C     39-40).  AA(I,1-8) = DERIVATIVES WITH RESPECT TO R,F,T,Q AT
C     J AND AT J+1.  AA(I,9) = THE RESIDUAL.  THE DERIVATIVES WITH
C     RESPECT TO T AND Q INCLUDE THE IMPLICIT VARIATION THROUGH
C     P(T,Q), E(T,Q), K(T,Q), AND EPSILON(T,Q).
C     ------------------------------------------------------------------
      SUBROUTINE ZONEQ(J,AA)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION AA(4,9)
      COMMON /GRID/ XI(201),EMPT(201),EMH(201),EMPH(201),N
      COMMON /VARBL/ R(201),F(201),T(201),Q(201),XH(201),X3A(201)
      COMMON /OLDT/ QN(201),EN(201),DTINV
      COMMON /THERM/ PP(201),DPT(201),DPQ(201),EE(201),DET(201),
     1   DEQ(201),CK(201),DKT(201),DKQ(201),CPA(201),EP(201),
     2   DEPT(201),DEPQ(201)
      COMMON /FLAGS/ ICV(201)
      COMMON /CONST/ G,SIG,ARAD,RGAS,PI,C256,C4PS,C8PI
      COMMON /STARP/ XM,XMI,ZMET,QHYD
      J1=J
      J2=J+1
      X1=XI(J1)
      X2=XI(J2)
      XS=X1+X2
      XD=X2-X1
      RS=R(J1)+R(J2)
      RD=R(J2)-R(J1)
      PS=PP(J1)+PP(J2)
      PD=PP(J2)-PP(J1)
      QS=Q(J1)+Q(J2)
      QD=Q(J2)-Q(J1)
      DO 10 I=1,4
      DO 10 K=1,9
   10 AA(I,K)=0.
C
C     EQUATION (22) - HYDROSTATIC EQUILIBRIUM
      WR=G*EMH(J)*(QS/PS)**3/(RS*RS)
      W=WR*RD
      AA(1,1)=-WR-2.*W/RS
      AA(1,5)=WR-2.*W/RS
      CP1=-1.-3.*W/PS
      CP2=1.-3.*W/PS
      AA(1,3)=CP1*DPT(J1)
      AA(1,4)=CP1*DPQ(J1)+3.*W/QS
      AA(1,7)=CP2*DPT(J2)
      AA(1,8)=CP2*DPQ(J2)+3.*W/QS
      AA(1,9)=PD+W
C
C     EQUATION (23) - MASS CONTINUITY
      QS3=QS**3
      AA(2,1)=QS3*RS*(RS-2.*RD)
      AA(2,5)=-QS3*RS*(RS+2.*RD)
      AA(2,4)=-3.*QS*QS*RS*RS*RD
      AA(2,8)=AA(2,4)
      AA(2,9)=C8PI*EMPH(J)*XD-QS3*RS*RS*RD
C
C     EQUATION (24) - ENERGY BALANCE WITH BACKWARD TIME
C     DIFFERENCES.  THE NUCLEAR RATE ENTERS AS THE GEOMETRIC MEAN
C     OF THE VALUES AT THE TWO POINTS.
      A4=3.*(PS/QS)**4
      A4P=4.*A4/PS
      A4Q=4.*A4/QS
      E1=EP(J1)
      E2=EP(J2)
      GE=0.
      GT1=0.
      GQ1=0.
      GT2=0.
      GQ2=0.
      IF (E1.LE.1.D-15 .OR. E2.LE.1.D-15) GO TO 20
      GE=2.*SQRT(E1*E2)
      GT1=0.5*GE*DEPT(J1)/E1
      GQ1=0.5*GE*DEPQ(J1)/E1
      GT2=0.5*GE*DEPT(J2)/E2
      GQ2=0.5*GE*DEPQ(J2)/E2
   20 CONTINUE
      DQT=Q(J1)+Q(J2)-QN(J1)-QN(J2)
      BR=GE-(EE(J1)+EE(J2)-EN(J1)-EN(J2))*DTINV+A4*DQT*DTINV
      CM=2.*EMPH(J)*XD
      BT1=GT1-DET(J1)*DTINV+A4P*DPT(J1)*DQT*DTINV
      BQ1=GQ1-DEQ(J1)*DTINV+(A4P*DPQ(J1)-A4Q)*DQT*DTINV+A4*DTINV
      BT2=GT2-DET(J2)*DTINV+A4P*DPT(J2)*DQT*DTINV
      BQ2=GQ2-DEQ(J2)*DTINV+(A4P*DPQ(J2)-A4Q)*DQT*DTINV+A4*DTINV
      AA(3,2)=XS*(X2-3.*X1)
      AA(3,6)=XS*(3.*X2-X1)
      AA(3,3)=-CM*BT1
      AA(3,4)=-CM*BQ1
      AA(3,7)=-CM*BT2
      AA(3,8)=-CM*BQ2
      AA(3,9)=F(J2)*XS*(3.*X2-X1)+F(J1)*XS*(X2-3.*X1)-CM*BR
C
      IF (ICV(J).EQ.1) GO TO 40
C
C     EQUATION (25) - RADIATIVE TRANSPORT
      CKS=CK(J1)+CK(J2)
      FS=F(J1)+F(J2)
      CW=XS*XS/EMH(J)
      CWF=CW*FS
      AA(4,2)=-CKS*CW*PD
      AA(4,6)=AA(4,2)
      AA(4,3)=-1.-CWF*(DKT(J1)*PD-CKS*DPT(J1))
      AA(4,7)=1.-CWF*(DKT(J2)*PD+CKS*DPT(J2))
      AA(4,4)=-CWF*(DKQ(J1)*PD-CKS*DPQ(J1))
      AA(4,8)=-CWF*(DKQ(J2)*PD+CKS*DPQ(J2))
      AA(4,9)=T(J2)-T(J1)-CKS*CWF*PD
      GO TO 50
C
C     EQUATION (26) - CONVECTIVE (ADIABATIC) TRANSPORT
   40 AA(4,3)=-DET(J1)-A4P*DPT(J1)*QD
      AA(4,7)=DET(J2)-A4P*DPT(J2)*QD
      AA(4,4)=-DEQ(J1)-(A4P*DPQ(J1)-A4Q)*QD+A4
      AA(4,8)=DEQ(J2)-(A4P*DPQ(J2)-A4Q)*QD-A4
      AA(4,9)=EE(J2)-EE(J1)-A4*QD
   50 RETURN
      END
C
C     ------------------------------------------------------------------
C     SUBROUTINE ENVEL - THE OUTER-ZONE (ENVELOPE) INTEGRATION,
C     TAKING THE PLACE OF THE ATMOSPHERE PROGRAM OF M. S. VARDYA
C     REFERRED TO IN THE PAPER.  GIVEN THE TOTAL RADIUS RS AND
C     LUMINOSITY XLS, THE PHOTOSPHERIC VALUES FOLLOW FROM
C          T(EFF) = (L/(4*PI*SIGMA*R**2))**(1/4)
C          KAPPA*P = (2/3)*G*M/R**2
C     AND THE ENVELOPE (MASS FRACTION DELS OF THE STAR, WITH
C     L TAKEN CONSTANT AND THE TIME TERMS NEGLECTED) IS THEN
C     INTEGRATED INWARD ON A LOGARITHMIC COLUMN-MASS SCALE WITH
C     THE HYDROSTATIC RELATION AND THE SMALLER OF THE RADIATIVE
C     AND ADIABATIC GRADIENTS.  RETURNED ARE THE FITTED VALUES
C     OF EQS. (30), (32), (33) AT THE OUTERMOST INTERIOR POINT -
C     RF (RADIUS), TF (TEMPERATURE), QF (CUBE ROOT OF DENSITY).
C     ------------------------------------------------------------------
      SUBROUTINE ENVEL(RS,XLS,XSU,RF,TF,QF)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      COMMON /CONST/ G,SIG,ARAD,RGAS,PI,C256,C4PS,C8PI
      COMMON /STARP/ XM,XMI,ZMET,QHYD
      COMMON /CTRL/ CLIM,EPSC,ITMAX,ALFA
      Y=1.-XSU-ZMET
      RMU=1.984*XSU+0.7495*Y+0.5*ZMET
      TE=SQRT(SQRT(XLS/(C4PS*RS*RS)))
C     PHOTOSPHERIC DENSITY BY A SHORT FIXED-POINT ITERATION
      RHO=1.D-7
      DO 10 I=1,25
      CALL OPAC(TE,RHO**0.3333333,XSU,ZMET,CPS,D1,D2)
      PSF=0.6666667*G*XM/(RS*RS*CPS)
      RHN=PSF/(RGAS*TE*RMU)
      RHO=SQRT(RHO*RHN)
   10 CONTINUE
      C64=3./(64.*PI*SIG*G)
      DELME=XM-XMI
      NE=120
      P=PSF
      TX=TE
      R3=RS**3
      XMU=0.
C     INWARD MARCH ON A LOGARITHMIC SCALE OF EXTERIOR COLUMN MASS
      DO 40 K=1,NE
      XMUN=DELME*10.**(6.*(DBLE(K)/DBLE(NE)-1.))
      DMU=XMUN-XMU
C     HYDROSTATIC STEP (STAGED TO AVOID OVERFLOW OF R**4)
      T1=G*XM/R3
      DP=T1*(DMU/(12.566371*R3**0.3333333))
      CALL OPAC(TX,RHO**0.3333333,XSU,ZMET,CPS,D1,D2)
      GRR=C64*CPS*(XLS/XM)*(P/TX**4)
C     WHERE THE LAYER IS UNSTABLE, THE GRADIENT COMES FROM THE
C     BOEHM-VITENSE (1958) MIXING-LENGTH THEORY, WITH ALPHA (THE
C     RATIO OF MIXING LENGTH TO PRESSURE SCALE HEIGHT) FREE.
C     THE CUBIC IN XI = SQRT(GRAD - GRADAD + U**2),
C        (XI-U)**3 + (8U/9)(XI**2 - U**2 - W) = 0,
C     WITH W = GRADRAD - GRADAD AND
C     U = 12 SIGMA T**3 SQRT(8 HP/GEE)/(CP RHO**2 KAPPA L**2),
C     IS SOLVED BY BISECTION.
      GRAD=GRR
      IF (GRR.LE.0.40) GO TO 34
      GEE=G*XM/R3**0.6666667
      HP=P/(RHO*GEE)
      CPHT=2.5*RGAS*RMU
      EL=ALFA*HP
      UMLT=12.*SIG*TX**3*SQRT(8.*HP/GEE)/(CPHT*RHO*RHO*CPS*EL*EL)
      WMLT=GRR-0.40
      X1B=UMLT
      X2B=SQRT(WMLT+UMLT*UMLT)
      DO 32 IB=1,45
      XMB=0.5*(X1B+X2B)
      FCB=(XMB-UMLT)**3+(8.*UMLT/9.)*(XMB*XMB-UMLT*UMLT-WMLT)
      IF (FCB.GT.0.) X2B=XMB
      IF (FCB.LE.0.) X1B=XMB
   32 CONTINUE
      GRAD=0.40+XMB*XMB-UMLT*UMLT
   34 CONTINUE
      PN=P+DP
      TX=TX*(PN/P)**GRAD
      P=PN
      PG=P-ARAD*TX**4/3.
      IF (PG.LT.0.1*P) PG=0.1*P
      RHO=PG/(RGAS*TX*RMU)
      R3=R3-DMU/(4.1887902*RHO)
      R3MIN=0.001*RS**3
      IF (R3.LT.R3MIN) R3=R3MIN
      XMU=XMUN
   40 CONTINUE
      RF=R3**0.3333333
      TF=TX
      QF=RHO**0.3333333
      RETURN
      END
C
C     ------------------------------------------------------------------
C     SUBROUTINE STATE - EQUATION OF STATE.  IDEAL GAS OF FULLY
C     IONIZED H, HE, AND METALS, PLUS RADIATION.  RETURNS THE
C     MODIFIED VARIABLE P = PRESSURE**(1/4) AND THE INTERNAL
C     ENERGY PER GRAM, WITH DERIVATIVES W.R.T. T AND Q.
C     DEGENERACY AND PARTIAL IONIZATION ARE OMITTED (SEE THE
C     REMARKS ON CONTINUITY IN SEC. V OF THE PAPER).
C     ------------------------------------------------------------------
      SUBROUTINE STATE(TT,QQ,RMU,PPX,DPTX,DPQX,EX,DETX,DEQX)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      COMMON /CONST/ G,SIG,ARAD,RGAS,PI,C256,C4PS,C8PI
      RHO=QQ**3
      PG=RGAS*RHO*TT*RMU
      PR=ARAD*TT**4/3.
      P=PG+PR
      PPX=SQRT(SQRT(P))
      C=0.25*PPX/P
      DPTX=C*(PG/TT+4.*PR/TT)
      DPQX=C*3.*PG/QQ
      EX=1.5*RGAS*TT*RMU+3.*PR/RHO
      DETX=1.5*RGAS*RMU+12.*PR/(RHO*TT)
      DEQX=-9.*PR/(RHO*QQ)
      RETURN
      END
C
C     ------------------------------------------------------------------
C     SUBROUTINE OPAC - OPACITY AND ITS DERIVATIVES.  ELECTRON
C     SCATTERING PLUS KRAMERS BOUND-FREE (GUILLOTINE FACTOR 10)
C     AND FREE-FREE, JOINED HARMONICALLY TO AN H-MINUS TERM FOR
C     THE COOL OUTER LAYERS,
C         KAPPA(H-) = 2.5E-31*(Z/0.02)*RHO**(1/2)*T**9.
C     THE HARMONIC JOIN KEEPS KAPPA AND ITS DERIVATIVES
C     CONTINUOUS, AS THE CONVERGENCE OF THE NEWTON-RAPHSON
C     PROCESS REQUIRES (SEC. V AND FIG. 3 OF THE PAPER).
C     ------------------------------------------------------------------
      SUBROUTINE OPAC(TT,QQ,X,Z,CAP,DCT,DCQ)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      RHO=QQ**3
      CES=0.19*(1.+X)
      CKR=(4.34D24*Z+3.68D22*(1.-Z))*(1.+X)*RHO/TT**3.5
      CHMLG=-70.48+LOG(50.*Z)+0.5*LOG(RHO)+9.*LOG(TT)
      IF (CHMLG.LT.-80.) CHMLG=-80.
      RCHM=0.
      IF (CHMLG.LT.80.) RCHM=EXP(-CHMLG)
      RKES=1./(CES+CKR)
      CAP=1./(RCHM+RKES)
      DCT=CAP*CAP*(9.*RCHM-3.5*RKES*RKES*CKR)/TT
      DCQ=CAP*CAP*(1.5*RCHM+3.*RKES*RKES*CKR)/QQ
      RETURN
      END
C
C     ------------------------------------------------------------------
C     SUBROUTINE ENUC - THERMONUCLEAR ENERGY GENERATION FROM THE
C     PP CHAIN WITH HE3 FOLLOWED AS AN EXPLICIT SPECIES, PLUS THE
C     CNO BI-CYCLE.  CHANNELS AND EFFECTIVE Q-VALUES (NEUTRINO
C     LOSSES REMOVED, BAHCALL 1989 CH. 3) -
C        P(P,E+ NU)D(P,G)HE3           Q =  6.671 MEV
C        HE3(HE3,2P)HE4                Q = 12.860 MEV
C        HE3(HE4,G)BE7 - PPII COMPLETION, NET HE3 + P TO HE4,
C                                      Q = 18.982 MEV
C        CNO, N14(P,G) BOTTLENECK      Q = 25.03  MEV
C     THE PPIII BRANCH OF BE7 IS NEGLECTED (UNDER ONE PER CENT OF
C     THE BE7 COMPLETIONS BELOW ABOUT 1.5E7 K).  THE PARKER,
C     BAHCALL + FOWLER (1964) BRANCHING RATIOS REMAIN TO BE
C     INSTALLED FOR HOT, HELIUM-RICH LATE MIXTURES.  RETURNS
C     EPSILON AND ITS PARTIAL DERIVATIVES WITH RESPECT TO T AND
C     Q AT FIXED COMPOSITION.
C     ------------------------------------------------------------------
      SUBROUTINE ENUC(TT,QQ,X,X3,Z,EPX,DEPTX,DEPQX)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      CALL RATES(TT,QQ,X,X3,Z,RPP,C33,C34,R14,DLPT,DL3T,DL4T,DLCT,
     1   DLPQ,DL3Q,DL4Q,DLCQ)
      E1=1.0688D-5*RPP
      E3=2.0604D-5*C33*X3*X3
      E4=3.0413D-5*C34*X3
      EC=4.0103D-5*R14
      EPX=E1+E3+E4+EC
      DEPTX=(E1*DLPT+E3*DL3T+E4*DL4T+EC*DLCT)/TT
      DEPQX=(E1*DLPQ+E3*DL3Q+E4*DL4Q+EC*DLCQ)/QQ
      RETURN
      END
C
C     ------------------------------------------------------------------
C     SUBROUTINE RATES - REACTION RATES OF THE PP CHAIN AND OF THE
C     CNO BOTTLENECK, PER GRAM PER SECOND, IN COEFFICIENT FORM -
C        R(PP)  = RPP        (PROPORTIONAL TO X1**2)
C        R(33)  = C33*X3**2
C        R(34)  = C34*X3
C        R(CNO) = R14
C     CROSS-SECTION FACTORS FROM CAUGHLAN + FOWLER (1988), THE
C     WORKING EQUIVALENT OF THE BAHCALL (1989) PRESCRIPTIONS USED
C     BY LBA97.  ELECTRON SCREENING AFTER GRABOSKE, DEWITT,
C     GROSSMAN + COOPER (1973) - EXACT DEBYE-HUECKEL WEAK
C     SCREENING, AND AN INTERMEDIATE FORM
C        H = 0.380 * LAMBDA0**0.860 * ZBAR58
C              * ((Z1+Z2)**1.86 - Z1**1.86 - Z2**1.86),
C     THE SMALLER OF THE TWO EXPONENTS BEING TAKEN.  THE
C     COMPOSITION FACTOR ZBAR58 (MEAN OF Z**1.58 OVER IONS) IS
C     CARRIED IN SIMPLIFIED FORM AND SHOULD BE CHECKED AGAINST
C     THE GDGC PAPER.  THE LOGARITHMIC DERIVATIVES OF EACH
C     COEFFICIENT WITH RESPECT TO LN T AND LN Q (SCREENING
C     INCLUDED) ARE ALSO RETURNED.
C     ------------------------------------------------------------------
      SUBROUTINE RATES(TT,QQ,X1,X3,Z,RPP,C33,C34,R14,
     1   DLPT,DL3T,DL4T,DLCT,DLPQ,DL3Q,DL4Q,DLCQ)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      RHO=QQ**3
      X4=MAX(1.-X1-X3-Z,0.D0)
      T9=1.D-9*TT
      T913=EXP(0.3333333333D0*LOG(T9))
      T923=T913*T913
      AVO=6.0221D23
C     SCREENING - WEAK (DEBYE-HUECKEL) AND INTERMEDIATE (GDGC 73)
      ZETA=1.984*X1+1.989*X3+1.499*X4+4.0*Z
      ANI=X1/1.008+X3/3.016+X4/4.003+Z/14.
      ANE=X1/1.008+2.*(X3/3.016+X4/4.003)+7.*Z/14.
      Z58=(X1/1.008+2.990*(X3/3.016+X4/4.003)+21.64*Z/14.)/ANI
      HW1=1.88D8*SQRT(RHO*ZETA)/(TT*SQRT(TT))
      ALAM0=1.88D8*SQRT(RHO*(ANI+ANE))/(TT*SQRT(TT))
      CI=0.380*Z58*EXP(0.860*LOG(ALAM0))
C     CHANNEL SCREENING EXPONENTS - PP (Z1*Z2=1), HE3+HE3 AND
C     HE3+HE4 (Z1*Z2=4), CNO (Z1*Z2=7)
      HP=HW1
      DFPT=-1.5*HP
      DFPQ=1.5*HP
      HPI=CI*1.6301
      IF (HPI.LT.HP) THEN
         HP=HPI
         DFPT=-1.29*HP
         DFPQ=1.29*HP
      END IF
      H3=4.*HW1
      DF3T=-1.5*H3
      DF3Q=1.5*H3
      H3I=CI*5.917
      IF (H3I.LT.H3) THEN
         H3=H3I
         DF3T=-1.29*H3
         DF3Q=1.29*H3
      END IF
      HC=7.*HW1
      DFCT=-1.5*HC
      DFCQ=1.5*HC
      HCI=CI*9.520
      IF (HCI.LT.HC) THEN
         HC=HCI
         DFCT=-1.29*HC
         DFCQ=1.29*HC
      END IF
      IF (HP.GT.6.) HP=6.
      IF (H3.GT.6.) H3=6.
      IF (HC.GT.6.) HC=6.
      FSP=EXP(HP)
      FS3=EXP(H3)
      FSC=EXP(HC)
C     P(P,E+ NU)D - CAUGHLAN + FOWLER (1988)
      SPP=0.
      DLPT=0.
      ARG=-3.380/T913
      IF (ARG.GT.-600.) THEN
         POL=1.+0.123*T913+1.09*T923+0.938*T9
         DPOL=0.0410*T913+0.7267*T923+0.938*T9
         SPP=4.01D-15/T923*EXP(ARG)*POL
         DLPT=-0.6666667+1.1267/T913+DPOL/POL+DFPT
      END IF
      RPP=RHO*X1*X1*AVO*SPP/2.032*FSP
      DLPQ=3.+DFPQ
C     HE3(HE3,2P)HE4
      S33=0.
      DL3T=0.
      ARG=-12.276/T913
      IF (ARG.GT.-600.) THEN
         POL=1.+0.034*T913-0.522*T923-0.124*T9+0.353*T9*T913
     1      +0.213*T9*T923
         DPOL=0.0113*T913-0.348*T923-0.124*T9+0.4707*T9*T913
     1      +0.355*T9*T923
         S33=6.04D10/T923*EXP(ARG)*POL
         DL3T=-0.6666667+4.092/T913+DPOL/POL+DF3T
      END IF
      C33=RHO*AVO*S33/18.19*FS3
      DL3Q=3.+DF3Q
C     HE3(HE4,G)BE7, COMPLETED THROUGH PPII
      S34=0.
      DL4T=0.
      W=1./(1.+0.0495*T9)
      T9A=T9*W
      ARG=-12.826/EXP(0.3333333333D0*LOG(T9A))
      IF (ARG.GT.-600.) THEN
         T9A56=EXP(0.8333333333D0*LOG(T9A))
         S34=5.61D6*T9A56/(T9*SQRT(T9))*EXP(ARG)
         DL4T=0.8333333*W-1.5-ARG*0.3333333*W+DF3T
      END IF
      C34=RHO*X4*AVO*S34/12.07*FS3
      DL4Q=3.+DF3Q
C     N14(P,G)O15 - THE CNO BOTTLENECK
      S2=0.
      S3=0.
      SR=0.
      DS=0.
      ARG=-15.228/T913-0.092*T9*T9
      IF (ARG.GT.-600.) THEN
         POL=1.+0.027*T913-0.778*T923-0.149*T9+0.261*T9*T913
     1      +0.127*T9*T923
         DPOL=0.0090*T913-0.5187*T923-0.149*T9+0.348*T9*T913
     1      +0.2117*T9*T923
         SR=4.90D7/T923*EXP(ARG)*POL
         DS=SR*(-0.6666667+5.076/T913-0.184*T9*T9+DPOL/POL)
      END IF
      ARG=-3.011/T9
      IF (ARG.GT.-600.) THEN
         S2=2.37D3/(T9*SQRT(T9))*EXP(ARG)
         DS=DS+S2*(-1.5+3.011/T9)
      END IF
      ARG=-12.53/T9
      IF (ARG.GT.-600.) THEN
         S3=2.19D4*EXP(ARG)
         DS=DS+S3*(12.53/T9)
      END IF
      S14=SR+S2+S3
      DLCT=0.
      IF (S14.GT.0.) DLCT=DS/S14+DFCT
      R14=RHO*X1*(Z/3.)*AVO*S14/14.115*FSC
      DLCQ=3.+DFCQ
      RETURN
      END
C
C     ------------------------------------------------------------------
C     SUBROUTINE BURN - ADVANCE THE COMPOSITION THROUGH THE TIME
C     STEP DT USING THE CONVERGED STRUCTURE.  HE3 IS ADVANCED BY A
C     BACKWARD-EULER STEP, WHICH REDUCES TO A QUADRATIC SOLVED IN
C     CLOSED FORM AND IS STABLE FOR TIME STEPS EITHER LARGE OR
C     SMALL COMPARED WITH THE HE3 LIFETIME (COMPARE THE CLOSING
C     REMARK OF HFG 1964 ON THE NUCLEAR SPECIES EQUATIONS).  H1
C     IS THEN ADVANCED EXPLICITLY WITH THE UPDATED HE3 RATES, AND
C     HE4 FOLLOWS FROM THE SUM RULE.  THE LARGEST RELATIVE HE3
C     CHANGE IS RETURNED FOR TIME STEP CONTROL.
C     ------------------------------------------------------------------
      SUBROUTINE BURN(DT)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      COMMON /GRID/ XI(201),EMPT(201),EMH(201),EMPH(201),N
      COMMON /VARBL/ R(201),F(201),T(201),Q(201),XH(201),X3A(201)
      COMMON /THERM/ PP(201),DPT(201),DPQ(201),EE(201),DET(201),
     1   DEQ(201),CK(201),DKT(201),DKQ(201),CPA(201),EP(201),
     2   DEPT(201),DEPQ(201)
      COMMON /STARP/ XM,XMI,ZMET,QHYD
      COMMON /BRNC/ DX3MX
      AVO=6.0221D23
      C3N=3.016/AVO
      C1N=1.008/AVO
      DX3MX=0.
      EPC=MAX(EP(1),1.D-30)
      DO 10 J=1,N
      X1=XH(J)
      X3=X3A(J)
      CALL RATES(T(J),Q(J),X1,X3,ZMET,RPP,C33,C34,R14,
     1   D1,D2,D3,D4,D5,D6,D7,D8)
      AQ=DT*C3N*2.*C33
      BQ=1.+DT*C3N*C34
      CQ=-(X3+DT*C3N*RPP)
      IF (AQ.GT.1.D-30) THEN
         X3N=(-BQ+SQRT(BQ*BQ-4.*AQ*CQ))/(2.*AQ)
      ELSE
         X3N=-CQ/BQ
      END IF
      IF (X3N.LT.0.) X3N=0.
      R33N=C33*X3N*X3N
      R34N=C34*X3N
      X1N=X1+DT*C1N*(-3.*RPP+2.*R33N-R34N-4.*R14)
      IF (X1N.LT.0.) X1N=0.
      IF (X1N+X3N.GT.1.-ZMET) X3N=MAX(1.-ZMET-X1N,0.D0)
C     THE HE3 STEP LIMITER CONSULTS ONLY POINTS THAT MATTER FOR
C     THE ENERGY BUDGET, SO THAT SLOW RELAXATION OF TRACE HE3 IN
C     THE COOL OUTER REGIONS CANNOT THROTTLE THE TIME STEP
      DXR=ABS(X3N-X3)/(X3N+1.D-3)
      IF (EP(J).GT.1.D-4*EPC .AND. DXR.GT.DX3MX) DX3MX=DXR
      XH(J)=X1N
      X3A(J)=X3N
   10 CONTINUE
      RETURN
      END
C
C     ------------------------------------------------------------------
C     SUBROUTINE MIX - INSTANTANEOUS MIXING OF THE HYDROGEN
C     ABUNDANCE OVER EACH CONTIGUOUS CONVECTIVE REGION (MASS
C     WEIGHTED MEAN OVER THE POINTS OF THE REGION).
C     ------------------------------------------------------------------
      SUBROUTINE MIX
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      COMMON /GRID/ XI(201),EMPT(201),EMH(201),EMPH(201),N
      COMMON /VARBL/ R(201),F(201),T(201),Q(201),XH(201),X3A(201)
      COMMON /FLAGS/ ICV(201)
      COMMON /STARP/ XM,XMI,ZMET,QHYD
      NM1=N-1
      J=1
   10 IF (ICV(J).EQ.0) GO TO 40
      K1=J
   20 IF (J.EQ.NM1) GO TO 25
      IF (ICV(J+1).EQ.0) GO TO 25
      J=J+1
      GO TO 20
   25 K2=J+1
      SW=0.
      SX=0.
      SX3=0.
      DO 30 JP=K1,K2
      W=0.
      IF (JP.EQ.1) W=EMH(1)
      IF (JP.GT.1 .AND. JP.LT.N) W=EMH(JP)-EMH(JP-1)
      IF (JP.EQ.N) W=XM-EMH(NM1)
      SW=SW+W
      SX=SX+W*XH(JP)
      SX3=SX3+W*X3A(JP)
   30 CONTINUE
      XB=SX/SW
      X3B=SX3/SW
      DO 35 JP=K1,K2
      XH(JP)=XB
   35 X3A(JP)=X3B
   40 J=J+1
      IF (J.LE.NM1) GO TO 10
      RETURN
      END
C
C     ------------------------------------------------------------------
C     SUBROUTINE PRINTM - PRINT THE RUN OF THE STRUCTURE
C     VARIABLES THROUGH THE MODEL ON UNIT 6.
C     ------------------------------------------------------------------
      SUBROUTINE PRINTM
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      COMMON /GRID/ XI(201),EMPT(201),EMH(201),EMPH(201),N
      COMMON /VARBL/ R(201),F(201),T(201),Q(201),XH(201),X3A(201)
      COMMON /THERM/ PP(201),DPT(201),DPQ(201),EE(201),DET(201),
     1   DEQ(201),CK(201),DKT(201),DKQ(201),CPA(201),EP(201),
     2   DEPT(201),DEPQ(201)
      COMMON /FLAGS/ ICV(201)
      COMMON /STARP/ XM,XMI,ZMET,QHYD
      WRITE (6,600)
      DO 10 J=1,N
      XL=XI(J)*XI(J)*F(J)
      RHO=Q(J)**3
      PRS=PP(J)**4
      ICP=0
      IF (J.LT.N) ICP=ICV(J)
      WRITE (6,601) J,XI(J),EMPT(J)/XM,R(J),XL,T(J),RHO,PRS,
     1   XH(J),X3A(J),CPA(J),EP(J),ICP
   10 CONTINUE
      RETURN
  600 FORMAT ('0','  J',6X,'XI',7X,'M/M',9X,'R',10X,'L',10X,
     1   'T',8X,'RHO',10X,'P',9X,'X',8X,'HE3',6X,'KAPPA',8X,
     2   'EPS',2X,'CV')
  601 FORMAT (' ',I3,0PF8.4,F9.5,1P9E11.3,I3)
      END
C     ------------------------------------------------------------------
C     F77 LINE, PHASE 2 - EXPLICIT HE3 NETWORK (SEE PLAN.md).
C     BUILD -  GFORTRAN -O -O HENYEY77 HENYEY77.F
C     RUN   -  ./HENYEY77 < DECK.IN
C     CARD 1 CARRIES AN OPTIONAL FOURTH FIELD, THE INITIAL HE3
C     MASS FRACTION.  BLANK OR ZERO IS THE LBA97 CONVENTION.  A
C     NEGATIVE VALUE SETS HE3 TO ITS LOCAL EQUILIBRIUM VALUE, FOR
C     COMPARISON WITH THE EQUILIBRIUM-CHAIN 1964 PROGRAM IN THE
C     REPOSITORY ROOT.
C     ------------------------------------------------------------------
